const i18n = {
  en: {
    modal_body_are_you_sure_you_want_to_reset_this_user_s_password_and_unlock_their_account_: "Are you sure you want to reset this user's password and unlock their account?",
    ph_https_maps_google_com: "https://maps.google.com/...",
    ph_e_g_slack_deal_notification: "e.g., Slack Deal Notification",
    ph_https_hooks_slack_com_services: "https://hooks.slack.com/services/...",
    ph_enter_full_name: "Enter full name",
    ph_optional: "Optional",
    ph_e_g_developer: "e.g. Developer",
    ph_e_g_graphic_video: "e.g. Graphic, Video",
    ph_https: "https://...",
    ph_e_g_5_hours: "e.g. 5 hours",
    ph_add_a_comment: "Add a comment...",

    html_user: "User",
    html_role: "Role",
    html_new_client: "New Client",
    html_deal_details: "Deal Details",
    html_select_method: "Select Method",
    html_phone_call: "Phone call",
    html_whatsapp: "WhatsApp",
    html_social_media: "Social media",
    html_deal_lost_reason: "Deal Lost Reason",
    html_why_was_this_deal_lost: "Why was this deal lost? *",
    html_order_details: "Order Details",
    html_not_confirmed: "Not Confirmed",
    html_in_progress: "In Progress",
    html_completed: "Completed",
    html_edit_order: "Edit Order",
    html_delete_order: "Delete Order?",
    html_are_you_sure_you_want_to_permanently_delete_this_order_this_action_cannot_be_undone: "Are you sure you want to permanently delete this order? This action cannot be undone.",
    html_cancel: "Cancel",
    html_delete: "Delete",
    html_new_webhook: "New Webhook",
    html_integration_name: "Integration Name *",
    html_target_url_post: "Target URL (POST) *",
    html_trigger_event: "Trigger Event *",
    html_all_events: "All Events",
    html_deal_won: "Deal Won",
    html_new_client_added: "New Client Added",
    html_new_task_created: "New Task Created",
    html_task_details_updated: "Task Details Updated",
    html_task_status_updated: "Task Status Updated",
    html_task_deleted: "Task Deleted",
    html_save_webhook: "Save Webhook",
    html_employee: "Employee",
    html_manager: "Manager",
    html_supervisor: "Supervisor",
    html_admin: "Admin",
    html_no_manager: "No Manager",
    html_save_changes: "Save Changes",
    html_delete_user: "Delete User",
    html_are_you_sure_you_want_to_delete_this_user: "Are you sure you want to delete this user?",
    html_this_action_cannot_be_undone: "This action cannot be undone.",
    html_request_type: "Request Type",
    html_leave_request: "Leave Request",
    html_it_support: "IT Support",
    html_loan: "Loan",
    html_early_leaving: "Early Leaving",
    html_payslip_print: "Payslip print",
    html_leave_type: "Leave Type",
    html_annual_vacation: "Annual/Vacation",
    html_sick_leave: "Sick Leave",
    html_unpaid_leave: "Unpaid Leave",
    html_bereavement: "Bereavement",
    html_maternity_paternity: "Maternity/Paternity",
    html_submit_request: "Submit Request",
    html_new_department: "New Department",
    html_department_name: "Department Name *",
    html_description: "Description",
    html_department_head: "Department Head",
    html_department_employees: "Department Employees",
    html_create_department: "Create Department",
    html_new_project: "New Project",
    html_select_type: "Select Type...",
    html_internal: "Internal",
    html_client: "Client",
    html_product: "Product",
    html_maintenance: "Maintenance",
    html_startup: "Startup",
    html_enterprise: "Enterprise",
    html_urgent: "Urgent",
    html_frontend: "Frontend",
    html_backend: "Backend",
    html_ui_ux: "UI/UX",
    html_bug: "Bug",
    html_feature: "Feature",
    html_create_project: "Create Project",
    html_edit_project: "Edit Project",
    html_confirm_action: "Confirm Action",
    html_are_you_sure: "Are you sure?",
    html_confirm: "Confirm",
    html_edit_task: "Edit Task",
    html_task_title: "Task Title",
    html_category: "Category",
    html_priority: "Priority",
    html_low: "Low",
    html_medium: "Medium",
    html_high: "High",
    html_project: "Project",
    html_assign_to: "Assign To",
    html_content_type: "Content Type",
    html_source_link: "Source Link",
    html_upload_link: "Upload Link",
    html_visibility: "Visibility",
    html_public_everyone: "Public (Everyone)",
    html_team_only: "Team Only",
    html_private: "Private",
    html_start_date: "Start Date",
    html_due_date: "Due Date",
    html_end_date: "End Date",
    html_est_time: "Est. Time",
    html_task_details: "Task Details",
    html_activity_comments: "Activity & Comments",
    html_send: "Send",

    ui_install_muqam_hr: "Install MUQAM HR",
    ui_install: "Install",
    ui_approve: "Approve",
    ui_reject: "Reject",
    ui_employee_requests: "Employee Requests",
    ui_employee_name: "Employee Name",
    ui_request_type: "Request Type",
    ui_leave_type: "Leave Type",
    ui_status: "Status",
    ui_actions: "Actions",
    ui_post: "Post",
    ui_title: "Title",
    ui_content: "Content",
    ui_role: "Role",
    ui_total_tasks: "Total Tasks",
    ui_completed: "Completed",
    ui_overdue: "Overdue",
    ui_completion_rate: "Completion Rate",
    ui_score: "Score",
    ui_rating: "Rating",
    ui_employee_performance_report: "Employee Performance Report",
    ui_category: "Category",
    ui_priority: "Priority",
    ui_project: "Project",
    ui_content_type: "Content Type",
    ui_source_link: "Source Link",
    ui_upload_link: "Upload Link",
    ui_error_loading_page: "Error Loading Page",
    ui_departments_management: "Departments Management",
    ui_description: "Description",
    ui_head: "Head",
    ui_clients_management: "Clients Management",
    ui_company: "Company",
    ui_email: "Email",
    ui_phone: "Phone",
    ui_orders: "Orders",
    ui_start_date: "Start Date",
    ui_end_date: "End Date",
    ui_location: "Location",
    ui_invoice_amount: "Invoice Amount",
    ui_project_status: "Project Status",
    ui_crm_pipeline: "CRM Pipeline",
    ui_: "\u0645\u0644\u0627\u062d\u0638\u0627\u062a",
    ui_unauthorized: "Unauthorized",
    ui_api_integrations_webhooks: "API Integrations (Webhooks)",
    ui_event_type: "Event Type",
    ui_url: "URL",
    ui_projects: "Projects",
    ui_error_loading_approvals: "Error loading approvals",
    ui_approvals_dashboard: "Approvals Dashboard",
    ui_assignee: "Assignee",
    ui_links: "Links",

    toast_user_not_found: "User not found.",
    toast_user_updated_successfully: "User updated successfully",
    toast_failed_to_update_user: "Failed to update user",
    toast_failed_to_reset_password: "Failed to reset password",
    toast_user_deleted_successfully: "User deleted successfully",
    toast_failed_to_delete_user: "Failed to delete user",
    toast_request_submitted_successfully: "Request submitted successfully",
    toast_failed_to_submit_request: "Failed to submit request",
    toast_failed_to_update_status: "Failed to update status",
    toast_failed_to_submit_leave: "Failed to submit leave",
    toast_password_updated_successfully: "Password updated successfully!",
    toast_clocked_in_successfully: "Clocked in successfully!",
    toast_error_clocking_in: "Error clocking in.",
    toast_no_active_clock_in_found_for_today: "No active clock-in found for today.",
    toast_clocked_out_successfully: "Clocked out successfully!",
    toast_error_clocking_out: "Error clocking out.",
    toast_failed_to_post_comment: "Failed to post comment",
    toast_please_upload_a_receipt: "Please upload a receipt.",
    toast_expense_submitted_for_approval: "Expense submitted for approval.",
    toast_error_submitting_expense: "Error submitting expense.",
    toast_user_created_successfully: "User created successfully!",
    toast_role_updated: "Role updated",
    toast_job_title_updated: "Job title updated",
    toast_failed_to_update_job_title: "Failed to update job title",
    toast_manager_assigned: "Manager assigned",
    toast_document_requested: "Document requested",
    toast_document_uploaded_successfully: "Document uploaded successfully!",
    toast_error_uploading_document: "Error uploading document.",
    toast_document_saved_successfully: "Document and file saved successfully!",
    toast_error_saving_document: "Error saving document.",
    toast_document_file_required: "Select a document file before saving.",
    toast_document_file_too_large: "The selected file must be 5 MB or smaller.",
    toast_document_file_type_invalid: "Select a PDF, PNG, or JPG file.",
    toast_document_expiry_notification_sent: "Expiry notification sent to the document contacts.",
    toast_document_expiry_notification_failed: "Document saved, but the expiry notification could not be sent.",
    toast_failed_to_send_message: "Failed to send message.",
    toast_profile_photo_updated: "Profile photo updated!",
    toast_error_updating_photo: "Error updating photo.",
    toast_profile_details_updated_successfully: "Profile details updated successfully!",
    toast_ai_parsed_and_created_task: "AI parsed and created task!",
    toast_failed_to_create_task: "Failed to create task: ",
    toast_task_created_successfully: "Task created successfully!",
    toast_task_sent_to_hussain_for_approval: "Task sent to Hussain for approval",
    toast_you_do_not_have_permission_to_modify_pending_approval_tasks: "You do not have permission to modify pending approval tasks",
    toast_failed_to_update_task_details: "Failed to update task details",
    toast_task_updated_successfully: "Task updated successfully",
    toast_failed_to_delete_task: "Failed to delete task",
    toast_task_deleted_successfully: "Task deleted successfully",
    toast_contract_saved_successfully: "Contract saved successfully",
    toast_deal_moved_to: "Deal moved to ",
    toast_failed_to_move_deal: "Failed to move deal",
    toast_deal_marked_as_lost_order_removed: "Deal marked as lost & order removed",
    toast_deal_marked_as_lost: "Deal marked as lost",
    toast_failed_to_update_deal: "Failed to update deal",
    toast_order_saved_and_deal_won: "Order saved and deal won!",
    toast_failed_to_save_order: "Failed to save order",
    toast_order_not_found: "Order not found",
    toast_order_updated_successfully: "Order updated successfully",
    toast_failed_to_update_order: "Failed to update order",
    toast_order_deleted_successfully: "Order deleted successfully",
    toast_failed_to_delete_order: "Failed to delete order",
    toast_department_deleted: "Department deleted",
    toast_failed_to_delete_department: "Failed to delete department.",
    toast_error_saving_department: "Error saving department",
    toast_client_deleted: "Client deleted",
    toast_failed_to_delete_client_it_might_be_linked_to_existing_deals: "Failed to delete client. It might be linked to existing deals.",
    toast_please_select_a_client: "Please select a client",
    toast_webhook_created: "Webhook created",
    toast_webhook_deleted: "Webhook deleted",
    toast_creating_project: "Creating project...",
    toast_project_created_successfully: "Project created successfully!",
    toast_failed_to_create_project: "Failed to create project",
    toast_updating_project: "Updating project...",
    toast_project_updated_successfully: "Project updated successfully!",
    toast_failed_to_update_project: "Failed to update project",
    toast_failed_to_update_task: "Failed to update task",
    toast_task: "Task ",
    modal_title_reset_password: "Reset Password",
    modal_body_are_you_sure_you_want_to_reset_this_user: "Are you sure you want to reset this user",
    modal_title_delete_user: "Delete User",
    modal_body_are_you_sure_you_want_to_delete_this_user_this_action_cannot_be_undone: "Are you sure you want to delete this user? This action cannot be undone.",
    modal_title_task_approval: "Task Approval",
    modal_body_are_you_sure_you_want_to: "Are you sure you want to ",

    nav_dashboard: "Dashboard",
    create_employment_contract: "Create Employment Contract",
    for_employee: "For Employee",
    employer_information: "Employer Information",
    employer_name_ar: "Employer Name (AR)",
    employer_name_en: "Employer Name (EN)",
    commercial_registration: "CR Number",
    employee_information: "Employee Information",
    employee_name: "Employee Name",
    nationality: "Nationality",
    identity_number: "ID / Iqama Number",
    job_details: "Job Details",
    work_arrangement: "Work Arrangement",
    commencement_date: "Commencement Date",
    contract_type_lbl: "Contract Type",
    end_date: "End Date",
    required_for_fixed: "Required for Fixed-term and Non-Saudis",
    probation_period: "Probation Period",
    enable_probation: "Subject to Probation?",
    probation_days: "Probation Days",
    compensation: "Compensation",
    basic_wage: "Basic Monthly Wage (SAR)",
    housing_allowance: "Housing Allowance",
    transport_allowance: "Transportation Allowance",
    total_monthly_wage: "Total Monthly Wage",
    save_as_draft: "Complete Later",
    submit_contract: "Submit Contract",
    contract_saved_draft: "Contract saved as draft.",
    contract_submitted: "Contract submitted successfully.",
    nav_time: "Time & Attendance",
    nav_leave: "Leave Management",
    nav_payroll: "Payroll",
    nav_performance: "Performance",
    nav_documents: "Documents",
    nav_users: "User Management",
    nav_profile: "My Profile",
    nav_tasks: "Tasks",
    nav_admin: "Admin Hub",
    nav_language: "Language: ",
    nav_theme: "Toggle Theme",
    nav_logout: "Logout",
    search_placeholder: "Search (Cmd/Ctrl + K)",
    role_employee: "Employee",
    welcome: "Good Morning, Sarah!",
    welcome_sub: "Here's what's happening today.",
    quick_actions: "Quick Actions",
    apply_leave: "Apply Leave",
    clock_in: "Clock In",
    view_payslip: "View Payslip",
    req_doc: "Request Document",
    leave_balances: "Leave Balances",
    annual_leave: "Annual",
    sick_leave: "Sick",
    unpaid_leave: "Unpaid",
    announcements: "Announcements",
    admin_overview: "Admin Overview",
    admin_sub: "Company HR snapshot",
    turnover_rate: "Turnover Rate",
    headcount: "Total Headcount",
    diversity: "Diversity Ratio",
    open_roles: "Open Roles",
    toast_clock_in: "Successfully clocked in at",
    toast_payroll_downloaded: 'Payslip downloaded successfully!',

    // Login
    login_title: 'Sign In to MUQAM',
    login_subtitle: 'Enter your credentials to access your portal',
    email_label: 'Email Address',
    password_label: 'Password',
    sign_in: 'Sign In',
    invalid_credentials: 'Invalid email or password',
    forgot_password: 'Forgot Password?',
    reset_password: 'Reset Password',
    send_reset_link: 'Send Reset Link',
    reset_email_instruction: 'Enter your email to receive a password reset link.',
    back_to_login: 'Back to Login',
    set_new_password: 'Set New Password',
    new_password_label: 'New Password',
    reset_link_sent: 'Password reset link sent to your email!',
    toast_leave_applied: "Leave request submitted successfully.",
    toast_doc_req: "Document requested. You will receive an email shortly.",
    toast_payslip: "Downloading payslip...",
    timesheet: "Weekly Timesheet",
    timesheet_sub: "Review your hours worked.",
    date: "Date",
    in: "In",
    out: "Out",
    hours: "Hours",
    status: "Status",
    leave_req: "Leave Request",
    leave_req_sub: "Apply for time off.",
    leave_type: "Leave Type",
    start_date: "Start Date",
    end_date: "End Date",
    reason: "Reason",
    submit: "Submit",
    pending_approvals: "Pending Approvals",
    approved: "Approved",
    pending: "Pending",
    rejected: "Rejected",
    salary_breakdown: "Salary Breakdown",
    salary_sub: "Your monthly compensation details.",
    basic: "Basic Salary",
    allowance: "Housing & Transport",
    deductions: "Tax & Deductions",
    net_pay: "Net Pay",
    recent_payslips: "Recent Payslips",
    month: "Month",
    download: "Download",
    dash_no_announcements: "No new announcements.",
    error_clock_in: "Error clocking in. Check DB connection.",
    success_clock_out: "Clocked out successfully.",
    error_clock_out: "Error clocking out.",
    failed_submit_leave: "Failed to submit leave",
    leave_req_status: "Leave request status updated",
    time_punch_type: "Punch Type",
    time_emp_id: "Employee ID",
    time_no_punches: "No recent time punches.",
    time_time: "Time",
    leave_no_reqs: "No leave requests found.",
    leave_employee: "Employee",
    leave_actions: "Actions",
    leave_annual_bal: "Annual Leave Balance",
    leave_sick_bal: "Sick Leave Balance",
    leave_unpaid_bal: "Unpaid Leave Taken",
    leave_days: "Days",
    leave_new_req: "New Request",
    leave_history: "Request History",
    leave_reject: "Reject",
    req_all: "All Requests",
    req_sub: "View and filter all Leave, Document, and Expense requests.",
    req_search: "Search",
    req_search_ph: "Search by name or details...",
    req_type: "Type",
    req_type_all: "All Types",
    req_type_leave: "Leave",
    req_type_doc: "Document",
    req_type_exp: "Expense",
    req_status: "Status",
    req_status_all: "All Statuses",
    req_pending: "Pending",
    req_approved: "Approved",
    req_rejected: "Rejected",
    req_details: "Details",
    req_no_found: "No requests found.",
    req_archived_title: "Archived Requests",
    req_archived_sub: "Historical record of completed requests.",
    req_orig_status: "Original Status",
    req_no_archived: "No archived requests found.",
    req_unauthorized: "Unauthorized. Only Admins and Managers can view Archived Requests.",
    req_archived_badge: "(Archived)",
    req_archive_btn: "Archive",
    exp_title: "Expenses",
    exp_sub: "Manage business expenses and reimbursements.",
    exp_new: "Submit New Expense",
    exp_amount: "Amount ($)",
    exp_desc: "Description",
    exp_receipt: "Receipt",
    exp_submit: "Submit Expense",
    exp_my: "My Expenses",
    exp_no_exp: "No expenses.",
    exp_download: "Download",
    exp_team_appr: "Team Expense Approvals",
    exp_no_pending: "No pending approvals.",
    exp_req_receipt: "Please upload a receipt.",
    pay_latest: "Latest Payslip",
    pay_base: "Base Salary",
    pay_extras: "Overtime/Bonus",
    pay_view_det: "View Details",
    pay_no_slips: "No payslips available.",
    pay_actions: "Actions",
    analy_title: "Analytics",
    analy_sub: "Overview of company metrics.",
    analy_growth: "Employee Growth",
    analy_leave: "Leave Trends",
    analy_unauth: "Unauthorized",
    admin_manage_tasks: "Manage Tasks",
    admin_time_reports: "Time Reports",
    admin_emp_dir: "Employee Directory",
    admin_docs: "Documents",
    admin_reg_users: "Registered Users",
    admin_pend_appr: "Pending Approvals",
    admin_req_attn: "Requires attention",
    admin_leave_inbox: "Leave Approvals Inbox",
    admin_no_pending: "No pending leave requests.",
    users_sub: "Manage employee accounts and permissions.",
    users_add_new: "Add New Employee",
    users_fn: "Full Name",
    users_fn_ph: "e.g. John Doe",
    users_iqama: "Iqama Number",
    users_iqama_ph: "e.g. 2xxxxxxxxx",
    users_phone: "Phone Number",
    users_phone_ph: "e.g. +9665xxxxxxx",
    users_email: "Email",
    users_temp_pass: "Temporary Password",
    users_job_title: "Job Title",
    users_job_ph: "e.g. Software Engineer",
    users_role: "Role",
    users_role_emp: "Employee",
    users_role_mgr: "Manager",
    users_role_admin: "Admin",
    users_create_acc: "Create Account",
    users_dir: "Employee Directory",
    users_details: "Employee Details",
    users_assign_role: "Assign Role",
    users_assign_mgr: "Assign Manager",
    users_contract: "Contract",
    users_no_mgr: "No Manager",
    contract_type: "Contract Type",
    contract_start: "Start Date",
    contract_end: "End Date (Optional)",
    contract_salary: "Monthly Salary",
    contract_status: "Status",
    contract_ft: "Full-time",
    contract_pt: "Part-time",
    contract_c: "Contractor",
    contract_fl: "Freelance",
    contract_active: "Active",
    contract_term: "Terminated",
    contract_exp: "Expired",
    contract_cancel: "Cancel",
    contract_save: "Save Contract",
    contract_housing: "Housing Allowance",
    contract_transport: "Transport Allowance",
    contract_other: "Other Allowances",
    contract_hours: "Working Hours",
    contract_probation: "Probation (Days)",
    contract_notice: "Notice Period (Days)",
    contract_leave: "Annual Leave (Days)",
    // Phase 2
    timeout_message: "Logged out due to 5 minutes of inactivity",
    nav_community: "Community",
    attendance_clock_in: "Clock In",
    attendance_clock_out: "Clock Out",
    attendance_location_office: "Logout from Office",
    attendance_location_order: "Logout from Order Location",
    post_announcement: "Post Announcement",
    news_hub: "News Hub (Saudi Arabia)",
    community_chat: "Community Wall",
    last_login: "Last Login",
    contract_expiring: "Contracts Expiring Soon",
    docs_expiring: "Documents Expiring Soon",
    birthday_msg: "🎉 Happy Birthday!",
    perf_sub: "Track your KPIs and goals.",
    perf_my_goals: "My Goals",
    perf_title_th: "Title",
    perf_due_date: "Due Date",
    perf_rating: "Rating",
    perf_no_goals: "No goals assigned yet.",
    doc_sub: "Upload official documents or request HR letters.",
    doc_upload_title: "Upload Official Document",
    doc_type: "Document Type",
    doc_file: "File",
    doc_upload_btn: "Upload Document",
    doc_save_btn: "Save",
    doc_no_file_selected: "No file selected",
    doc_file_help: "PDF, PNG, or JPG; maximum 5 MB.",
    doc_all_uploaded: "All Uploaded Documents",
    doc_my_uploaded: "My Uploaded Documents",
    doc_file_name: "File Name",
    doc_no_uploaded: "No uploaded documents.",
    doc_document_id: "Document ID",
    doc_document_name: "Document Name",
    doc_owner_name: "Owner Name",
    doc_owner_email: "Owner Email",
    doc_responsible_name: "Responsible Name",
    doc_responsible_email: "Responsible Email",
    doc_expiry_date: "Expiry Date",
    doc_days_left: "Days Left",
    doc_notified_30_days: "Notified 30 Days",
    doc_owner_phone: "Owner Phone",
    doc_auto_generated: "Auto-generated when saved",
    doc_status_expired: "Expired",
    doc_status_expiring_soon: "Expires Soon",
    doc_status_active: "Active",
    doc_yes: "Yes",
    doc_action_view: "View",
    doc_action_edit: "Edit",
    doc_action_print: "Print",
    doc_action_delete: "Delete",
    doc_view_title: "Document Details",
    doc_edit_title: "Edit Document",
    doc_print_title: "Document Record",
    doc_open_stored_file: "Open Stored File",
    doc_not_found: "Document not found.",
    doc_no_stored_file: "No stored file is available for this document.",
    doc_popup_blocked: "Allow pop-ups to open the stored file.",
    doc_action_not_allowed: "You do not have permission to change this document.",
    doc_update_success: "Document updated successfully.",
    doc_update_failed: "Failed to update document.",
    doc_delete_title: "Delete Document",
    doc_delete_confirm: "Are you sure you want to delete this document? This action cannot be undone.",
    doc_delete_success: "Document deleted successfully.",
    doc_delete_failed: "Failed to delete document.",
    password_reset_button: "Set New Password",
    password_reset_title: "Set New Password",
    password_reset_for: "Set a new password for",
    password_reset_new: "New Password",
    password_reset_confirm: "Confirm New Password",
    password_reset_show: "Show passwords",
    password_reset_hint: "Use at least 8 characters. The password is not displayed or stored after submission.",
    password_reset_submit: "Set Password",
    password_reset_minimum: "The new password must contain at least 8 characters.",
    password_reset_mismatch: "The password confirmation does not match.",
    password_reset_success: "Password updated and account unlocked successfully.",
    password_reset_admin_only: "Only an administrator can reset another user's password.",
    doc_req_letter: "Request Letter",
    doc_purpose: "Purpose",
    doc_submit_req: "Submit Request",
    doc_all_reqs: "All Letter Requests",
    doc_my_reqs: "My Requests",
    doc_no_reqs: "No requests found.",
    doc_type_passport: "Passport",
    doc_type_iqama: "Iqama",
    doc_type_contract: "Contract",
    doc_type_cert: "Certificate",
    doc_type_salary: "Salary Certificate",
    doc_type_noc: "NOC (No Objection Certificate)",
    doc_type_emp: "Employment Letter",
    msg_title: "Messages",
    msg_no_other: "No other users found.",
    msg_select: "Select a user to start messaging",
    msg_chat_with: "Chat with",
    msg_refresh: "Refresh",
    msg_loading: "Loading messages...",
    msg_type_ph: "Type a message...",
    msg_send: "Send",
    msg_no_msgs: "No messages yet. Say hi!",
    prof_sub: "Manage your account settings and personal information.",
    prof_update_pic: "Update Profile Picture",
    prof_upload_photo: "Upload Photo",
    prof_acc_details: "Account Details",
    prof_fn: "Full Name",
    prof_email: "Email Address",
    prof_iqama: "Iqama Number",
    prof_phone: "Phone Number",
    prof_save: "Save Changes",
    prof_security: "Security",
    prof_new_pass: "New Password",
    prof_new_pass_ph: "Enter new password",
    prof_update_pass: "Update Password",
    task_sub: "Track projects and manage team tasks.",
    task_assign_new: "Assign New Task",
    task_title: "Task Title",
    task_assign_to: "Assign To",
    task_sel_emp: "Select Employee",
    task_due: "Due Date",
    task_assign_btn: "Assign Task",
    task_due_lbl: "Due:",
    task_no_date: "No date",
    task_assigned_lbl: "Assigned:",
    task_unknown: "Unknown",
    task_todo: "To Do",
    task_working: "Working",
    task_done: "Done",
    task_no_tasks: "No tasks in this list",
    nav_emp_dir: "Employees & Contracts",
    emp_dir_sub: "Directory of personnel and their contract details.",
    emp_dir_company: "Company Directory",
    emp_name: "Employee Name",
    emp_contact: "Contact Info",
    emp_role_title: "Role / Title",
    emp_na: "N/A",
    emp_no_title: "No Title",
    notif_title: "Notifications",
    notif_login: "Please log in to view notifications.",
    notif_no_found: "No notifications found.",
    notif_sub: "View all your system alerts and messages.",
    notif_new: "New",
    notif_no_dropdown: "No notifications",
    nav_coming_soon: "Coming Soon",
    nav_under_const: "Module under construction"
  },
  ar: {
    modal_body_are_you_sure_you_want_to_reset_this_user_s_password_and_unlock_their_account_: "Are you sure you want to reset this user's password and unlock their account?",
    ph_https_maps_google_com: "https://maps.google.com/...",
    ph_e_g_slack_deal_notification: "e.g., Slack Deal Notification",
    ph_https_hooks_slack_com_services: "https://hooks.slack.com/services/...",
    ph_enter_full_name: "Enter full name",
    ph_optional: "Optional",
    ph_e_g_developer: "e.g. Developer",
    ph_e_g_graphic_video: "e.g. Graphic, Video",
    ph_https: "https://...",
    ph_e_g_5_hours: "e.g. 5 hours",
    ph_add_a_comment: "Add a comment...",

    html_user: "User",
    html_role: "Role",
    html_new_client: "New Client",
    html_deal_details: "Deal Details",
    html_select_method: "Select Method",
    html_phone_call: "Phone call",
    html_whatsapp: "WhatsApp",
    html_social_media: "Social media",
    html_deal_lost_reason: "Deal Lost Reason",
    html_why_was_this_deal_lost: "Why was this deal lost? *",
    html_order_details: "Order Details",
    html_not_confirmed: "Not Confirmed",
    html_in_progress: "In Progress",
    html_completed: "Completed",
    html_edit_order: "Edit Order",
    html_delete_order: "Delete Order?",
    html_are_you_sure_you_want_to_permanently_delete_this_order_this_action_cannot_be_undone: "Are you sure you want to permanently delete this order? This action cannot be undone.",
    html_cancel: "Cancel",
    html_delete: "Delete",
    html_new_webhook: "New Webhook",
    html_integration_name: "Integration Name *",
    html_target_url_post: "Target URL (POST) *",
    html_trigger_event: "Trigger Event *",
    html_all_events: "All Events",
    html_deal_won: "Deal Won",
    html_new_client_added: "New Client Added",
    html_new_task_created: "New Task Created",
    html_task_details_updated: "Task Details Updated",
    html_task_status_updated: "Task Status Updated",
    html_task_deleted: "Task Deleted",
    html_save_webhook: "Save Webhook",
    html_employee: "Employee",
    html_manager: "Manager",
    html_supervisor: "Supervisor",
    html_admin: "Admin",
    html_no_manager: "No Manager",
    html_save_changes: "Save Changes",
    html_delete_user: "Delete User",
    html_are_you_sure_you_want_to_delete_this_user: "Are you sure you want to delete this user?",
    html_this_action_cannot_be_undone: "This action cannot be undone.",
    html_request_type: "Request Type",
    html_leave_request: "Leave Request",
    html_it_support: "IT Support",
    html_loan: "Loan",
    html_early_leaving: "Early Leaving",
    html_payslip_print: "Payslip print",
    html_leave_type: "Leave Type",
    html_annual_vacation: "Annual/Vacation",
    html_sick_leave: "Sick Leave",
    html_unpaid_leave: "Unpaid Leave",
    html_bereavement: "Bereavement",
    html_maternity_paternity: "Maternity/Paternity",
    html_submit_request: "Submit Request",
    html_new_department: "New Department",
    html_department_name: "Department Name *",
    html_description: "Description",
    html_department_head: "Department Head",
    html_department_employees: "Department Employees",
    html_create_department: "Create Department",
    html_new_project: "New Project",
    html_select_type: "Select Type...",
    html_internal: "Internal",
    html_client: "Client",
    html_product: "Product",
    html_maintenance: "Maintenance",
    html_startup: "Startup",
    html_enterprise: "Enterprise",
    html_urgent: "Urgent",
    html_frontend: "Frontend",
    html_backend: "Backend",
    html_ui_ux: "UI/UX",
    html_bug: "Bug",
    html_feature: "Feature",
    html_create_project: "Create Project",
    html_edit_project: "Edit Project",
    html_confirm_action: "Confirm Action",
    html_are_you_sure: "Are you sure?",
    html_confirm: "Confirm",
    html_edit_task: "Edit Task",
    html_task_title: "Task Title",
    html_category: "Category",
    html_priority: "Priority",
    html_low: "Low",
    html_medium: "Medium",
    html_high: "High",
    html_project: "Project",
    html_assign_to: "Assign To",
    html_content_type: "Content Type",
    html_source_link: "Source Link",
    html_upload_link: "Upload Link",
    html_visibility: "Visibility",
    html_public_everyone: "Public (Everyone)",
    html_team_only: "Team Only",
    html_private: "Private",
    html_start_date: "Start Date",
    html_due_date: "Due Date",
    html_end_date: "End Date",
    html_est_time: "Est. Time",
    html_task_details: "Task Details",
    html_activity_comments: "Activity & Comments",
    html_send: "Send",

    ui_install_muqam_hr: "Install MUQAM HR",
    ui_install: "Install",
    ui_approve: "Approve",
    ui_reject: "Reject",
    ui_employee_requests: "Employee Requests",
    ui_employee_name: "Employee Name",
    ui_request_type: "Request Type",
    ui_leave_type: "Leave Type",
    ui_status: "Status",
    ui_actions: "Actions",
    ui_post: "Post",
    ui_title: "Title",
    ui_content: "Content",
    ui_role: "Role",
    ui_total_tasks: "Total Tasks",
    ui_completed: "Completed",
    ui_overdue: "Overdue",
    ui_completion_rate: "Completion Rate",
    ui_score: "Score",
    ui_rating: "Rating",
    ui_employee_performance_report: "Employee Performance Report",
    ui_category: "Category",
    ui_priority: "Priority",
    ui_project: "Project",
    ui_content_type: "Content Type",
    ui_source_link: "Source Link",
    ui_upload_link: "Upload Link",
    ui_error_loading_page: "Error Loading Page",
    ui_departments_management: "Departments Management",
    ui_description: "Description",
    ui_head: "Head",
    ui_clients_management: "Clients Management",
    ui_company: "Company",
    ui_email: "Email",
    ui_phone: "Phone",
    ui_orders: "Orders",
    ui_start_date: "Start Date",
    ui_end_date: "End Date",
    ui_location: "Location",
    ui_invoice_amount: "Invoice Amount",
    ui_project_status: "Project Status",
    ui_crm_pipeline: "CRM Pipeline",
    ui_: "\u0645\u0644\u0627\u062d\u0638\u0627\u062a",
    ui_unauthorized: "Unauthorized",
    ui_api_integrations_webhooks: "API Integrations (Webhooks)",
    ui_event_type: "Event Type",
    ui_url: "URL",
    ui_projects: "Projects",
    ui_error_loading_approvals: "Error loading approvals",
    ui_approvals_dashboard: "Approvals Dashboard",
    ui_assignee: "Assignee",
    ui_links: "Links",

    toast_user_not_found: "User not found.",
    toast_user_updated_successfully: "User updated successfully",
    toast_failed_to_update_user: "Failed to update user",
    toast_failed_to_reset_password: "Failed to reset password",
    toast_user_deleted_successfully: "User deleted successfully",
    toast_failed_to_delete_user: "Failed to delete user",
    toast_request_submitted_successfully: "Request submitted successfully",
    toast_failed_to_submit_request: "Failed to submit request",
    toast_failed_to_update_status: "Failed to update status",
    toast_failed_to_submit_leave: "Failed to submit leave",
    toast_password_updated_successfully: "Password updated successfully!",
    toast_clocked_in_successfully: "Clocked in successfully!",
    toast_error_clocking_in: "Error clocking in.",
    toast_no_active_clock_in_found_for_today: "No active clock-in found for today.",
    toast_clocked_out_successfully: "Clocked out successfully!",
    toast_error_clocking_out: "Error clocking out.",
    toast_failed_to_post_comment: "Failed to post comment",
    toast_please_upload_a_receipt: "Please upload a receipt.",
    toast_expense_submitted_for_approval: "Expense submitted for approval.",
    toast_error_submitting_expense: "Error submitting expense.",
    toast_user_created_successfully: "User created successfully!",
    toast_role_updated: "Role updated",
    toast_job_title_updated: "Job title updated",
    toast_failed_to_update_job_title: "Failed to update job title",
    toast_manager_assigned: "Manager assigned",
    toast_document_requested: "Document requested",
    toast_document_uploaded_successfully: "Document uploaded successfully!",
    toast_error_uploading_document: "Error uploading document.",
    toast_document_saved_successfully: "تم حفظ المستند والملف بنجاح!",
    toast_error_saving_document: "حدث خطأ أثناء حفظ المستند.",
    toast_document_file_required: "اختر ملف المستند قبل الحفظ.",
    toast_document_file_too_large: "يجب ألا يتجاوز حجم الملف المحدد 5 ميجابايت.",
    toast_document_file_type_invalid: "اختر ملف PDF أو PNG أو JPG.",
    toast_document_expiry_notification_sent: "تم إرسال إشعار انتهاء الصلاحية إلى جهات اتصال المستند.",
    toast_document_expiry_notification_failed: "تم حفظ المستند، ولكن تعذر إرسال إشعار انتهاء الصلاحية.",
    toast_failed_to_send_message: "Failed to send message.",
    toast_profile_photo_updated: "Profile photo updated!",
    toast_error_updating_photo: "Error updating photo.",
    toast_profile_details_updated_successfully: "Profile details updated successfully!",
    toast_ai_parsed_and_created_task: "AI parsed and created task!",
    toast_failed_to_create_task: "Failed to create task: ",
    toast_task_created_successfully: "Task created successfully!",
    toast_task_sent_to_hussain_for_approval: "Task sent to Hussain for approval",
    toast_you_do_not_have_permission_to_modify_pending_approval_tasks: "You do not have permission to modify pending approval tasks",
    toast_failed_to_update_task_details: "Failed to update task details",
    toast_task_updated_successfully: "Task updated successfully",
    toast_failed_to_delete_task: "Failed to delete task",
    toast_task_deleted_successfully: "Task deleted successfully",
    toast_contract_saved_successfully: "Contract saved successfully",
    toast_deal_moved_to: "Deal moved to ",
    toast_failed_to_move_deal: "Failed to move deal",
    toast_deal_marked_as_lost_order_removed: "Deal marked as lost & order removed",
    toast_deal_marked_as_lost: "Deal marked as lost",
    toast_failed_to_update_deal: "Failed to update deal",
    toast_order_saved_and_deal_won: "Order saved and deal won!",
    toast_failed_to_save_order: "Failed to save order",
    toast_order_not_found: "Order not found",
    toast_order_updated_successfully: "Order updated successfully",
    toast_failed_to_update_order: "Failed to update order",
    toast_order_deleted_successfully: "Order deleted successfully",
    toast_failed_to_delete_order: "Failed to delete order",
    toast_department_deleted: "Department deleted",
    toast_failed_to_delete_department: "Failed to delete department.",
    toast_error_saving_department: "Error saving department",
    toast_client_deleted: "Client deleted",
    toast_failed_to_delete_client_it_might_be_linked_to_existing_deals: "Failed to delete client. It might be linked to existing deals.",
    toast_please_select_a_client: "Please select a client",
    toast_webhook_created: "Webhook created",
    toast_webhook_deleted: "Webhook deleted",
    toast_creating_project: "Creating project...",
    toast_project_created_successfully: "Project created successfully!",
    toast_failed_to_create_project: "Failed to create project",
    toast_updating_project: "Updating project...",
    toast_project_updated_successfully: "Project updated successfully!",
    toast_failed_to_update_project: "Failed to update project",
    toast_failed_to_update_task: "Failed to update task",
    toast_task: "Task ",
    modal_title_reset_password: "Reset Password",
    modal_body_are_you_sure_you_want_to_reset_this_user: "Are you sure you want to reset this user",
    modal_title_delete_user: "Delete User",
    modal_body_are_you_sure_you_want_to_delete_this_user_this_action_cannot_be_undone: "Are you sure you want to delete this user? This action cannot be undone.",
    modal_title_task_approval: "Task Approval",
    modal_body_are_you_sure_you_want_to: "Are you sure you want to ",

    nav_dashboard: "لوحة القيادة",
    nav_time: "الوقت والحضور",
    nav_leave: "إدارة الإجازات",
    nav_payroll: "الرواتب",
    nav_performance: "الأداء",
    nav_documents: "المستندات",
    nav_users: "إدارة المستخدمين",
    nav_profile: "ملفي الشخصي",
    nav_tasks: "المهام",
    nav_admin: "لوحة تحكم المسؤول",
    nav_language: "اللغة: ",
    nav_theme: "تغيير المظهر",
    nav_logout: "تسجيل الخروج",
    search_placeholder: "بحث (Cmd/Ctrl + K)",
    role_employee: "موظف",
    welcome: "صباح الخير، سارة!",
    welcome_sub: "إليك ما يحدث اليوم.",
    quick_actions: "إجراءات سريعة",
    apply_leave: "طلب إجازة",
    clock_in: "تسجيل الدخول",
    view_payslip: "عرض قسيمة الراتب",
    req_doc: "طلب مستند",
    leave_balances: "أرصدة الإجازات",
    annual_leave: "سنوية",
    sick_leave: "مرضية",
    unpaid_leave: "غير مدفوعة",
    announcements: "الإعلانات",
    admin_overview: "نظرة عامة للإدارة",
    admin_sub: "لقطة لبيانات الموارد البشرية",
    turnover_rate: "معدل الدوران",
    headcount: "إجمالي الموظفين",
    diversity: "نسبة التنوع",
    open_roles: "الوظائف المتاحة",
    toast_clock_in: "تم تسجيل الدخول بنجاح في",
    toast_payroll_downloaded: 'تم تحميل قسيمة الراتب بنجاح!',

    // Login (Arabic)
    login_title: 'تسجيل الدخول إلى مقام',
    login_subtitle: 'أدخل بيانات الاعتماد الخاصة بك للوصول إلى بوابتك',
    email_label: 'البريد الإلكتروني',
    password_label: 'كلمة المرور',
    sign_in: 'تسجيل الدخول',
    invalid_credentials: 'البريد الإلكتروني أو كلمة المرور غير صالحة',
    forgot_password: 'هل نسيت كلمة المرور؟',
    reset_password: 'إعادة تعيين كلمة المرور',
    send_reset_link: 'إرسال رابط إعادة التعيين',
    reset_email_instruction: 'أدخل بريدك الإلكتروني لتلقي رابط إعادة تعيين كلمة المرور.',
    back_to_login: 'العودة لتسجيل الدخول',
    set_new_password: 'تعيين كلمة مرور جديدة',
    new_password_label: 'كلمة المرور الجديدة',
    reset_link_sent: 'تم إرسال رابط إعادة تعيين كلمة المرور إلى بريدك الإلكتروني!',
    
    toast_leave_applied: "تم إرسال طلب الإجازة بنجاح.",
    toast_doc_req: "تم طلب المستند. ستتلقى بريدًا إلكترونيًا قريبًا.",
    toast_payslip: "جاري تحميل قسيمة الراتب...",
    timesheet: "الجدول الزمني الأسبوعي",
    timesheet_sub: "مراجعة ساعات عملك.",
    date: "التاريخ",
    in: "دخول",
    out: "خروج",
    hours: "الساعات",
    status: "الحالة",
    leave_req: "طلب إجازة",
    leave_req_sub: "التقدم بطلب للحصول على إجازة.",
    leave_type: "نوع الإجازة",
    start_date: "تاريخ البدء",
    end_date: "تاريخ الانتهاء",
    reason: "السبب",
    submit: "إرسال",
    pending_approvals: "الموافقات المعلقة",
    approved: "مقبول",
    pending: "قيد الانتظار",
    rejected: "مرفوض",
    salary_breakdown: "تفاصيل الراتب",
    salary_sub: "تفاصيل التعويض الشهري.",
    basic: "الراتب الأساسي",
    allowance: "السكن والنقل",
    deductions: "الضرائب والخصومات",
    net_pay: "صافي الراتب",
    recent_payslips: "قسائم الراتب الأخيرة",
    month: "الشهر",
    download: "تحميل",
    dash_no_announcements: "لا توجد إعلانات جديدة.",
    error_clock_in: "خطأ في تسجيل الدخول. تحقق من الاتصال بقاعدة البيانات.",
    success_clock_out: "تم تسجيل الخروج بنجاح.",
    error_clock_out: "خطأ في تسجيل الخروج.",
    failed_submit_leave: "فشل في تقديم الإجازة",
    leave_req_status: "تم تحديث حالة طلب الإجازة",
    time_punch_type: "نوع التسجيل",
    time_emp_id: "معرف الموظف",
    time_no_punches: "لا توجد تسجيلات وقت حديثة.",
    time_time: "الوقت",
    leave_no_reqs: "لم يتم العثور على طلبات إجازة.",
    leave_employee: "الموظف",
    leave_actions: "الإجراءات",
    leave_annual_bal: "رصيد الإجازة السنوية",
    leave_sick_bal: "رصيد الإجازة المرضية",
    leave_unpaid_bal: "الإجازة غير المدفوعة المتخذة",
    leave_days: "أيام",
    leave_new_req: "طلب جديد",
    leave_history: "سجل الطلبات",
    leave_reject: "رفض",
    req_all: "جميع الطلبات",
    req_sub: "عرض وتصفية جميع طلبات الإجازات والمستندات والنفقات.",
    req_search: "بحث",
    req_search_ph: "ابحث بالاسم أو التفاصيل...",
    req_type: "النوع",
    req_type_all: "جميع الأنواع",
    req_type_leave: "إجازة",
    req_type_doc: "مستند",
    req_type_exp: "نفقة",
    req_status: "الحالة",
    req_status_all: "جميع الحالات",
    req_pending: "قيد الانتظار",
    req_approved: "مقبول",
    req_rejected: "مرفوض",
    req_details: "التفاصيل",
    req_no_found: "لم يتم العثور على طلبات.",
    req_archived_title: "الطلبات المؤرشفة",
    req_archived_sub: "السجل التاريخي للطلبات المكتملة.",
    req_orig_status: "الحالة الأصلية",
    req_no_archived: "لم يتم العثور على طلبات مؤرشفة.",
    req_unauthorized: "غير مصرح لك. فقط المسؤولون والمديرون يمكنهم عرض الطلبات المؤرشفة.",
    req_archived_badge: "(مؤرشف)",
    req_archive_btn: "أرشفة",
    exp_title: "النفقات",
    exp_sub: "إدارة نفقات العمل والاسترداد.",
    exp_new: "تقديم نفقة جديدة",
    exp_amount: "المبلغ ($)",
    exp_desc: "الوصف",
    exp_receipt: "الإيصال",
    exp_submit: "تقديم النفقة",
    exp_my: "نفقاتي",
    exp_no_exp: "لا توجد نفقات.",
    exp_download: "تحميل",
    exp_team_appr: "موافقات نفقات الفريق",
    exp_no_pending: "لا توجد موافقات معلقة.",
    exp_req_receipt: "يرجى رفع الإيصال.",
    pay_latest: "أحدث قسيمة راتب",
    pay_base: "الراتب الأساسي",
    pay_extras: "العمل الإضافي/المكافأة",
    pay_view_det: "عرض التفاصيل",
    pay_no_slips: "لا توجد قسائم راتب متاحة.",
    pay_actions: "الإجراءات",
    analy_title: "التحليلات",
    analy_sub: "نظرة عامة على مقاييس الشركة.",
    analy_growth: "نمو الموظفين",
    analy_leave: "اتجاهات الإجازات",
    analy_unauth: "غير مصرح",
    admin_manage_tasks: "إدارة المهام",
    admin_time_reports: "تقارير الوقت",
    admin_emp_dir: "دليل الموظفين",
    admin_docs: "المستندات",
    admin_reg_users: "المستخدمين المسجلين",
    admin_pend_appr: "الموافقات المعلقة",
    admin_req_attn: "يتطلب الاهتمام",
    admin_leave_inbox: "صندوق الموافقات على الإجازات",
    admin_no_pending: "لا توجد طلبات إجازة معلقة.",
    users_sub: "إدارة حسابات الموظفين والصلاحيات.",
    users_add_new: "إضافة موظف جديد",
    users_fn: "الاسم الكامل",
    users_fn_ph: "مثال: أحمد محمد",
    users_iqama: "رقم الإقامة",
    users_iqama_ph: "مثال: 2xxxxxxxxx",
    users_phone: "رقم الهاتف",
    users_phone_ph: "مثال: +9665xxxxxxx",
    users_email: "البريد الإلكتروني",
    users_temp_pass: "كلمة مرور مؤقتة",
    users_job_title: "المسمى الوظيفي",
    users_job_ph: "مثال: مهندس برمجيات",
    users_role: "الدور",
    users_role_emp: "موظف",
    users_role_mgr: "مدير",
    users_role_admin: "مسؤول",
    users_create_acc: "إنشاء حساب",
    users_dir: "دليل الموظفين",
    users_details: "تفاصيل الموظف",
    users_assign_role: "تعيين الدور",
    users_assign_mgr: "تعيين المدير",
    users_contract: "العقد",
    users_no_mgr: "بدون مدير",
    contract_type: "نوع العقد",
    contract_ft: "دوام كامل",
    contract_pt: "دوام جزئي",
    contract_c: "مقاول",
    contract_start: "تاريخ البدء",
    contract_end: "تاريخ الانتهاء (اختياري)",
    contract_salary: "الراتب الشهري",
    contract_status: "الحالة",
    contract_fl: "عمل حر",
    contract_active: "نشط",
    contract_term: "تم الإنهاء",
    contract_exp: "منتهي",
    contract_cancel: "إلغاء",
    contract_save: "حفظ العقد",
    contract_housing: "بدل السكن",
    contract_transport: "بدل النقل",
    contract_other: "بدلات أخرى",
    contract_hours: "ساعات العمل",
    contract_probation: "فترة التجربة (أيام)",
    contract_notice: "فترة الإشعار (أيام)",
    contract_leave: "الإجازة السنوية (أيام)",
    // Phase 2
    timeout_message: "تم تسجيل الخروج بسبب 5 دقائق من الخمول",
    nav_community: "المجتمع",
    attendance_clock_in: "تسجيل الدخول",
    attendance_clock_out: "تسجيل الخروج",
    attendance_location_office: "الخروج من المكتب",
    attendance_location_order: "الخروج من موقع الطلب",
    post_announcement: "نشر إعلان",
    news_hub: "أخبار السعودية",
    community_chat: "حائط المجتمع",
    last_login: "آخر تسجيل دخول",
    contract_expiring: "عقود تنتهي قريباً",
    docs_expiring: "مستندات تنتهي قريباً",
    birthday_msg: "🎉 عيد ميلاد سعيد!",
    perf_sub: "تتبع مؤشرات الأداء والأهداف الخاصة بك.",
    perf_my_goals: "أهدافي",
    perf_title_th: "العنوان",
    perf_due_date: "تاريخ الاستحقاق",
    perf_rating: "التقييم",
    perf_no_goals: "لم يتم تعيين أي أهداف بعد.",
    doc_sub: "رفع المستندات الرسمية أو طلب خطابات الموارد البشرية.",
    doc_upload_title: "رفع مستند رسمي",
    doc_type: "نوع المستند",
    doc_file: "الملف",
    doc_upload_btn: "رفع المستند",
    doc_save_btn: "حفظ",
    doc_no_file_selected: "لم يتم اختيار ملف",
    doc_file_help: "PDF أو PNG أو JPG؛ بحد أقصى 5 ميجابايت.",
    doc_all_uploaded: "جميع المستندات المرفوعة",
    doc_my_uploaded: "مستنداتي المرفوعة",
    doc_file_name: "اسم الملف",
    doc_no_uploaded: "لا توجد مستندات مرفوعة.",
    doc_document_id: "معرف المستند",
    doc_document_name: "اسم المستند",
    doc_owner_name: "اسم المالك",
    doc_owner_email: "البريد الإلكتروني للمالك",
    doc_responsible_name: "اسم المسؤول",
    doc_responsible_email: "البريد الإلكتروني للمسؤول",
    doc_expiry_date: "تاريخ الانتهاء",
    doc_days_left: "الأيام المتبقية",
    doc_notified_30_days: "تم الإشعار قبل 30 يوماً",
    doc_owner_phone: "هاتف المالك",
    doc_auto_generated: "يتم إنشاؤه تلقائياً عند الحفظ",
    doc_status_expired: "منتهي",
    doc_status_expiring_soon: "ينتهي قريباً",
    doc_status_active: "ساري",
    doc_yes: "نعم",
    doc_action_view: "عرض",
    doc_action_edit: "تعديل",
    doc_action_print: "طباعة",
    doc_action_delete: "حذف",
    doc_view_title: "تفاصيل المستند",
    doc_edit_title: "تعديل المستند",
    doc_print_title: "سجل المستند",
    doc_open_stored_file: "فتح الملف المحفوظ",
    doc_not_found: "لم يتم العثور على المستند.",
    doc_no_stored_file: "لا يوجد ملف محفوظ لهذا المستند.",
    doc_popup_blocked: "اسمح بالنوافذ المنبثقة لفتح الملف المحفوظ.",
    doc_action_not_allowed: "ليس لديك صلاحية لتغيير هذا المستند.",
    doc_update_success: "تم تحديث المستند بنجاح.",
    doc_update_failed: "تعذر تحديث المستند.",
    doc_delete_title: "حذف المستند",
    doc_delete_confirm: "هل أنت متأكد من حذف هذا المستند؟ لا يمكن التراجع عن هذا الإجراء.",
    doc_delete_success: "تم حذف المستند بنجاح.",
    doc_delete_failed: "تعذر حذف المستند.",
    password_reset_button: "تعيين كلمة مرور جديدة",
    password_reset_title: "تعيين كلمة مرور جديدة",
    password_reset_for: "تعيين كلمة مرور جديدة لـ",
    password_reset_new: "كلمة المرور الجديدة",
    password_reset_confirm: "تأكيد كلمة المرور الجديدة",
    password_reset_show: "إظهار كلمات المرور",
    password_reset_hint: "استخدم 8 أحرف على الأقل. لن يتم عرض كلمة المرور أو تخزينها بعد الإرسال.",
    password_reset_submit: "تعيين كلمة المرور",
    password_reset_minimum: "يجب أن تتكون كلمة المرور الجديدة من 8 أحرف على الأقل.",
    password_reset_mismatch: "تأكيد كلمة المرور غير متطابق.",
    password_reset_success: "تم تحديث كلمة المرور وفتح الحساب بنجاح.",
    password_reset_admin_only: "يمكن للمسؤول فقط إعادة تعيين كلمة مرور مستخدم آخر.",
    doc_req_letter: "طلب خطاب",
    doc_purpose: "الغرض",
    doc_submit_req: "تقديم الطلب",
    doc_all_reqs: "جميع طلبات الخطابات",
    doc_my_reqs: "طلباتي",
    doc_no_reqs: "لم يتم العثور على طلبات.",
    doc_type_passport: "جواز السفر",
    doc_type_iqama: "إقامة",
    doc_type_contract: "عقد",
    doc_type_cert: "شهادة",
    doc_type_salary: "شهادة راتب",
    doc_type_noc: "شهادة عدم ممانعة",
    doc_type_emp: "خطاب عمل",
    msg_title: "الرسائل",
    msg_no_other: "لم يتم العثور على مستخدمين آخرين.",
    msg_select: "اختر مستخدماً لبدء المراسلة",
    msg_chat_with: "الدردشة مع",
    msg_refresh: "تحديث",
    msg_loading: "جاري تحميل الرسائل...",
    msg_type_ph: "اكتب رسالة...",
    msg_send: "إرسال",
    msg_no_msgs: "لا توجد رسائل بعد. قل مرحباً!",
    prof_sub: "إدارة إعدادات حسابك والمعلومات الشخصية.",
    prof_update_pic: "تحديث الصورة الشخصية",
    prof_upload_photo: "رفع الصورة",
    prof_acc_details: "تفاصيل الحساب",
    prof_fn: "الاسم الكامل",
    prof_email: "البريد الإلكتروني",
    prof_iqama: "رقم الإقامة",
    prof_phone: "رقم الهاتف",
    prof_save: "حفظ التغييرات",
    prof_security: "الأمان",
    prof_new_pass: "كلمة مرور جديدة",
    prof_new_pass_ph: "أدخل كلمة المرور الجديدة",
    prof_update_pass: "تحديث كلمة المرور",
    task_sub: "تتبع المشاريع وإدارة مهام الفريق.",
    task_assign_new: "تعيين مهمة جديدة",
    task_title: "عنوان المهمة",
    task_assign_to: "تعيين إلى",
    task_sel_emp: "اختر الموظف",
    task_due: "تاريخ الاستحقاق",
    task_assign_btn: "تعيين المهمة",
    task_due_lbl: "الاستحقاق:",
    task_no_date: "بدون تاريخ",
    task_assigned_lbl: "معينة لـ:",
    task_unknown: "غير معروف",
    task_todo: "للقيام بها",
    task_working: "جاري العمل",
    task_done: "مكتملة",
    task_no_tasks: "لا توجد مهام في هذه القائمة",
    nav_emp_dir: "الموظفون والعقود",
    emp_dir_sub: "دليل الموظفين وتفاصيل عقودهم.",
    emp_dir_company: "دليل الشركة",
    emp_name: "اسم الموظف",
    emp_contact: "معلومات الاتصال",
    emp_role_title: "الدور / المسمى الوظيفي",
    emp_na: "غير متوفر",
    emp_no_title: "بدون مسمى",
    notif_title: "الإشعارات",
    notif_login: "يرجى تسجيل الدخول لعرض الإشعارات.",
    notif_no_found: "لا توجد إشعارات.",
    notif_sub: "عرض جميع تنبيهات النظام والرسائل الخاصة بك.",
    notif_new: "جديد",
    notif_no_dropdown: "لا توجد إشعارات",
    nav_coming_soon: "قريباً",
    nav_under_const: "الوحدة قيد الإنشاء"
  }
};
