const i18n = {
  en: {
    nav_dashboard: "Dashboard",
    nav_time: "Time & Attendance",
    nav_leave: "Leave Management",
    nav_payroll: "Payroll",
    nav_admin: "Admin Hub",
    search_placeholder: "Search (Cmd/Ctrl + K)",
    role_employee: "Employee",
    welcome: "Good Morning, Sarah!",
    welcome_sub: "Here's what's happening today.",
    quick_actions: "Quick Actions",
    apply_leave: "Apply Leave",
    clock_in: "Clock In",
    view_payslip: "View Payslip",
    req_doc: "Request Document",
    leave_balances: "Leave Balances",
    annual_leave: "Annual",
    sick_leave: "Sick",
    unpaid_leave: "Unpaid",
    announcements: "Announcements",
    admin_overview: "Workforce Analytics",
    admin_sub: "Executive HR summary and metrics.",
    turnover_rate: "Turnover Rate",
    headcount: "Active Headcount",
    diversity: "Diversity Ratio",
    open_roles: "Open Roles",
    toast_clock_in: "Successfully clocked in at",
    toast_payroll_downloaded: 'Payslip downloaded successfully!',

    // Login
    login_title: 'Sign In to Aegis',
    login_subtitle: 'Enter your credentials to access your portal',
    email_label: 'Email Address',
    password_label: 'Password',
    sign_in: 'Sign In',
    invalid_credentials: 'Invalid email or password',
    toast_leave_applied: "Leave request submitted successfully.",
    toast_doc_req: "Document requested. You will receive an email shortly.",
    toast_payslip: "Downloading payslip...",
    timesheet: "Weekly Timesheet",
    timesheet_sub: "Review your hours worked.",
    date: "Date",
    in: "In",
    out: "Out",
    hours: "Hours",
    status: "Status",
    leave_req: "Leave Request",
    leave_req_sub: "Apply for time off.",
    leave_type: "Leave Type",
    start_date: "Start Date",
    end_date: "End Date",
    reason: "Reason",
    submit: "Submit",
    pending_approvals: "Pending Approvals",
    approved: "Approved",
    pending: "Pending",
    rejected: "Rejected",
    salary_breakdown: "Salary Breakdown",
    salary_sub: "Your monthly compensation details.",
    basic: "Basic Salary",
    allowance: "Housing & Transport",
    deductions: "Tax & Deductions",
    net_pay: "Net Pay",
    recent_payslips: "Recent Payslips",
    month: "Month",
    download: "Download"
  },
  ar: {
    nav_dashboard: "لوحة القيادة",
    nav_time: "الوقت والحضور",
    nav_leave: "إدارة الإجازات",
    nav_payroll: "الرواتب",
    nav_admin: "مركز الإدارة",
    search_placeholder: "بحث (Cmd/Ctrl + K)",
    role_employee: "موظف",
    welcome: "صباح الخير، سارة!",
    welcome_sub: "إليك ما يحدث اليوم.",
    quick_actions: "إجراءات سريعة",
    apply_leave: "طلب إجازة",
    clock_in: "تسجيل الدخول",
    view_payslip: "عرض قسيمة الراتب",
    req_doc: "طلب مستند",
    leave_balances: "أرصدة الإجازات",
    annual_leave: "سنوية",
    sick_leave: "مرضية",
    unpaid_leave: "غير مدفوعة",
    announcements: "الإعلانات",
    admin_overview: "تحليلات القوى العاملة",
    admin_sub: "ملخص تنفيذي ومقاييس الموارد البشرية.",
    turnover_rate: "معدل الدوران",
    headcount: "إجمالي الموظفين",
    diversity: "نسبة التنوع",
    open_roles: "الوظائف المتاحة",
    toast_clock_in: "تم تسجيل الدخول بنجاح في",
    toast_payroll_downloaded: 'تم تحميل قسيمة الراتب بنجاح!',

    // Login (Arabic)
    login_title: 'تسجيل الدخول إلى إيجيس',
    login_subtitle: 'أدخل بيانات الاعتماد الخاصة بك للوصول إلى بوابتك',
    email_label: 'البريد الإلكتروني',
    password_label: 'كلمة المرور',
    sign_in: 'تسجيل الدخول',
    invalid_credentials: 'البريد الإلكتروني أو كلمة المرور غير صالحة',
    
    toast_leave_applied: "تم إرسال طلب الإجازة بنجاح.",
    toast_doc_req: "تم طلب المستند. ستتلقى بريدًا إلكترونيًا قريبًا.",
    toast_payslip: "جاري تحميل قسيمة الراتب...",
    timesheet: "الجدول الزمني الأسبوعي",
    timesheet_sub: "مراجعة ساعات عملك.",
    date: "التاريخ",
    in: "دخول",
    out: "خروج",
    hours: "الساعات",
    status: "الحالة",
    leave_req: "طلب إجازة",
    leave_req_sub: "التقدم بطلب للحصول على إجازة.",
    leave_type: "نوع الإجازة",
    start_date: "تاريخ البدء",
    end_date: "تاريخ الانتهاء",
    reason: "السبب",
    submit: "إرسال",
    pending_approvals: "الموافقات المعلقة",
    approved: "مقبول",
    pending: "قيد الانتظار",
    rejected: "مرفوض",
    salary_breakdown: "تفاصيل الراتب",
    salary_sub: "تفاصيل التعويض الشهري.",
    basic: "الراتب الأساسي",
    allowance: "السكن والنقل",
    deductions: "الضرائب والخصومات",
    net_pay: "صافي الراتب",
    recent_payslips: "قسائم الراتب الأخيرة",
    month: "الشهر",
    download: "تحميل"
  }
};
