const i18n = {
  en: {
    nav_dashboard: "Dashboard",
    nav_time: "Time & Attendance",
    nav_leave: "Leave Management",
    nav_payroll: "Payroll",
    nav_performance: "Performance",
    nav_documents: "Documents",
    nav_users: "User Management",
    nav_profile: "My Profile",
    nav_tasks: "Tasks",
    nav_admin: "Admin Hub",
    nav_language: "Language: ",
    nav_theme: "Toggle Theme",
    nav_logout: "Logout",
    search_placeholder: "Search (Cmd/Ctrl + K)",
    role_employee: "Employee",
    welcome: "Good Morning, Sarah!",
    welcome_sub: "Here's what's happening today.",
    quick_actions: "Quick Actions",
    apply_leave: "Apply Leave",
    clock_in: "Clock In",
    view_payslip: "View Payslip",
    req_doc: "Request Document",
    leave_balances: "Leave Balances",
    annual_leave: "Annual",
    sick_leave: "Sick",
    unpaid_leave: "Unpaid",
    announcements: "Announcements",
    admin_overview: "Admin Overview",
    admin_sub: "Company HR snapshot",
    turnover_rate: "Turnover Rate",
    headcount: "Total Headcount",
    diversity: "Diversity Ratio",
    open_roles: "Open Roles",
    toast_clock_in: "Successfully clocked in at",
    toast_payroll_downloaded: 'Payslip downloaded successfully!',

    // Login
    login_title: 'Sign In to MUQAM',
    login_subtitle: 'Enter your credentials to access your portal',
    email_label: 'Email Address',
    password_label: 'Password',
    sign_in: 'Sign In',
    invalid_credentials: 'Invalid email or password',
    toast_leave_applied: "Leave request submitted successfully.",
    toast_doc_req: "Document requested. You will receive an email shortly.",
    toast_payslip: "Downloading payslip...",
    timesheet: "Weekly Timesheet",
    timesheet_sub: "Review your hours worked.",
    date: "Date",
    in: "In",
    out: "Out",
    hours: "Hours",
    status: "Status",
    leave_req: "Leave Request",
    leave_req_sub: "Apply for time off.",
    leave_type: "Leave Type",
    start_date: "Start Date",
    end_date: "End Date",
    reason: "Reason",
    submit: "Submit",
    pending_approvals: "Pending Approvals",
    approved: "Approved",
    pending: "Pending",
    rejected: "Rejected",
    salary_breakdown: "Salary Breakdown",
    salary_sub: "Your monthly compensation details.",
    basic: "Basic Salary",
    allowance: "Housing & Transport",
    deductions: "Tax & Deductions",
    net_pay: "Net Pay",
    recent_payslips: "Recent Payslips",
    month: "Month",
    download: "Download",
    dash_no_announcements: "No new announcements.",
    error_clock_in: "Error clocking in. Check DB connection.",
    success_clock_out: "Clocked out successfully.",
    error_clock_out: "Error clocking out.",
    failed_submit_leave: "Failed to submit leave",
    leave_req_status: "Leave request status updated",
    time_punch_type: "Punch Type",
    time_emp_id: "Employee ID",
    time_no_punches: "No recent time punches.",
    time_time: "Time",
    leave_no_reqs: "No leave requests found.",
    leave_employee: "Employee",
    leave_actions: "Actions",
    leave_annual_bal: "Annual Leave Balance",
    leave_sick_bal: "Sick Leave Balance",
    leave_unpaid_bal: "Unpaid Leave Taken",
    leave_days: "Days",
    leave_new_req: "New Request",
    leave_history: "Request History",
    leave_reject: "Reject",
    req_all: "All Requests",
    req_sub: "View and filter all Leave, Document, and Expense requests.",
    req_search: "Search",
    req_search_ph: "Search by name or details...",
    req_type: "Type",
    req_type_all: "All Types",
    req_type_leave: "Leave",
    req_type_doc: "Document",
    req_type_exp: "Expense",
    req_status: "Status",
    req_status_all: "All Statuses",
    req_pending: "Pending",
    req_approved: "Approved",
    req_rejected: "Rejected",
    req_details: "Details",
    req_no_found: "No requests found.",
    req_archived_title: "Archived Requests",
    req_archived_sub: "Historical record of completed requests.",
    req_orig_status: "Original Status",
    req_no_archived: "No archived requests found.",
    req_unauthorized: "Unauthorized. Only Admins and Managers can view Archived Requests.",
    req_archived_badge: "(Archived)",
    req_archive_btn: "Archive",
    exp_title: "Expenses",
    exp_sub: "Manage business expenses and reimbursements.",
    exp_new: "Submit New Expense",
    exp_amount: "Amount ($)",
    exp_desc: "Description",
    exp_receipt: "Receipt",
    exp_submit: "Submit Expense",
    exp_my: "My Expenses",
    exp_no_exp: "No expenses.",
    exp_download: "Download",
    exp_team_appr: "Team Expense Approvals",
    exp_no_pending: "No pending approvals.",
    exp_req_receipt: "Please upload a receipt.",
    pay_latest: "Latest Payslip",
    pay_base: "Base Salary",
    pay_extras: "Overtime/Bonus",
    pay_view_det: "View Details",
    pay_no_slips: "No payslips available.",
    pay_actions: "Actions",
    analy_title: "Analytics",
    analy_sub: "Overview of company metrics.",
    analy_growth: "Employee Growth",
    analy_leave: "Leave Trends",
    analy_unauth: "Unauthorized",
    admin_manage_tasks: "Manage Tasks",
    admin_time_reports: "Time Reports",
    admin_emp_dir: "Employee Directory",
    admin_docs: "Documents",
    admin_reg_users: "Registered Users",
    admin_pend_appr: "Pending Approvals",
    admin_req_attn: "Requires attention",
    admin_leave_inbox: "Leave Approvals Inbox",
    admin_no_pending: "No pending leave requests.",
    users_sub: "Manage employee accounts and permissions.",
    users_add_new: "Add New Employee",
    users_fn: "Full Name",
    users_fn_ph: "e.g. John Doe",
    users_iqama: "Iqama Number",
    users_iqama_ph: "e.g. 2xxxxxxxxx",
    users_phone: "Phone Number",
    users_phone_ph: "e.g. +9665xxxxxxx",
    users_email: "Email",
    users_temp_pass: "Temporary Password",
    users_job_title: "Job Title",
    users_job_ph: "e.g. Software Engineer",
    users_role: "Role",
    users_role_emp: "Employee",
    users_role_mgr: "Manager",
    users_role_admin: "Admin",
    users_create_acc: "Create Account",
    users_dir: "Employee Directory",
    users_details: "Employee Details",
    users_assign_role: "Assign Role",
    users_assign_mgr: "Assign Manager",
    users_contract: "Contract",
    users_no_mgr: "No Manager",
    contract_type: "Contract Type",
    contract_ft: "Full-time",
    contract_pt: "Part-time",
    contract_c: "Contractor",
    contract_fl: "Freelance",
    contract_start: "Start Date",
    contract_end: "End Date (Optional)",
    contract_salary: "Salary (Monthly)",
    contract_status: "Status",
    contract_active: "Active",
    contract_term: "Terminated",
    contract_exp: "Expired",
    contract_cancel: "Cancel",
    contract_save: "Save Contract",
    perf_sub: "Track your KPIs and goals.",
    perf_my_goals: "My Goals",
    perf_title_th: "Title",
    perf_due_date: "Due Date",
    perf_rating: "Rating",
    perf_no_goals: "No goals assigned yet.",
    doc_sub: "Upload official documents or request HR letters.",
    doc_upload_title: "Upload Official Document",
    doc_type: "Document Type",
    doc_file: "File",
    doc_upload_btn: "Upload Document",
    doc_all_uploaded: "All Uploaded Documents",
    doc_my_uploaded: "My Uploaded Documents",
    doc_file_name: "File Name",
    doc_no_uploaded: "No uploaded documents.",
    doc_req_letter: "Request Letter",
    doc_purpose: "Purpose",
    doc_submit_req: "Submit Request",
    doc_all_reqs: "All Letter Requests",
    doc_my_reqs: "My Requests",
    doc_no_reqs: "No requests found.",
    doc_type_passport: "Passport",
    doc_type_iqama: "Iqama",
    doc_type_contract: "Contract",
    doc_type_cert: "Certificate",
    doc_type_salary: "Salary Certificate",
    doc_type_noc: "NOC (No Objection Certificate)",
    doc_type_emp: "Employment Letter",
    msg_title: "Messages",
    msg_no_other: "No other users found.",
    msg_select: "Select a user to start messaging",
    msg_chat_with: "Chat with",
    msg_refresh: "Refresh",
    msg_loading: "Loading messages...",
    msg_type_ph: "Type a message...",
    msg_send: "Send",
    msg_no_msgs: "No messages yet. Say hi!",
    prof_sub: "Manage your account settings and personal information.",
    prof_update_pic: "Update Profile Picture",
    prof_upload_photo: "Upload Photo",
    prof_acc_details: "Account Details",
    prof_fn: "Full Name",
    prof_email: "Email Address",
    prof_iqama: "Iqama Number",
    prof_phone: "Phone Number",
    prof_save: "Save Changes",
    prof_security: "Security",
    prof_new_pass: "New Password",
    prof_new_pass_ph: "Enter new password",
    prof_update_pass: "Update Password",
    nav_tasks: "Tasks",
    task_sub: "Track projects and manage team tasks.",
    task_assign_new: "Assign New Task",
    task_title: "Task Title",
    task_assign_to: "Assign To",
    task_sel_emp: "Select Employee",
    task_due: "Due Date",
    task_assign_btn: "Assign Task",
    task_due_lbl: "Due:",
    task_no_date: "No date",
    task_assigned_lbl: "Assigned:",
    task_unknown: "Unknown",
    task_todo: "To Do",
    task_working: "Working",
    task_done: "Done",
    task_no_tasks: "No tasks in this list",
    nav_emp_dir: "Employees & Contracts",
    emp_dir_sub: "Directory of personnel and their contract details.",
    emp_dir_company: "Company Directory",
    emp_name: "Employee Name",
    emp_contact: "Contact Info",
    emp_role_title: "Role / Title",
    emp_na: "N/A",
    emp_no_title: "No Title",
    notif_title: "Notifications",
    notif_login: "Please log in to view notifications.",
    notif_no_found: "No notifications found.",
    notif_sub: "View all your system alerts and messages.",
    notif_new: "New",
    notif_no_dropdown: "No notifications",
    nav_coming_soon: "Coming Soon",
    nav_under_const: "Module under construction"
  },
  ar: {
    nav_dashboard: "لوحة القيادة",
    nav_time: "الوقت والحضور",
    nav_leave: "إدارة الإجازات",
    nav_payroll: "الرواتب",
    nav_performance: "الأداء",
    nav_documents: "المستندات",
    nav_users: "إدارة المستخدمين",
    nav_profile: "ملفي الشخصي",
    nav_tasks: "المهام",
    nav_admin: "لوحة تحكم المسؤول",
    nav_language: "اللغة: ",
    nav_theme: "تغيير المظهر",
    nav_logout: "تسجيل الخروج",
    search_placeholder: "بحث (Cmd/Ctrl + K)",
    role_employee: "موظف",
    welcome: "صباح الخير، سارة!",
    welcome_sub: "إليك ما يحدث اليوم.",
    quick_actions: "إجراءات سريعة",
    apply_leave: "طلب إجازة",
    clock_in: "تسجيل الدخول",
    view_payslip: "عرض قسيمة الراتب",
    req_doc: "طلب مستند",
    leave_balances: "أرصدة الإجازات",
    annual_leave: "سنوية",
    sick_leave: "مرضية",
    unpaid_leave: "غير مدفوعة",
    announcements: "الإعلانات",
    admin_overview: "نظرة عامة للإدارة",
    admin_sub: "لقطة لبيانات الموارد البشرية",
    turnover_rate: "معدل الدوران",
    headcount: "إجمالي الموظفين",
    diversity: "نسبة التنوع",
    open_roles: "الوظائف المتاحة",
    toast_clock_in: "تم تسجيل الدخول بنجاح في",
    toast_payroll_downloaded: 'تم تحميل قسيمة الراتب بنجاح!',

    // Login (Arabic)
    login_title: 'تسجيل الدخول إلى مقام',
    login_subtitle: 'أدخل بيانات الاعتماد الخاصة بك للوصول إلى بوابتك',
    email_label: 'البريد الإلكتروني',
    password_label: 'كلمة المرور',
    sign_in: 'تسجيل الدخول',
    invalid_credentials: 'البريد الإلكتروني أو كلمة المرور غير صالحة',
    
    toast_leave_applied: "تم إرسال طلب الإجازة بنجاح.",
    toast_doc_req: "تم طلب المستند. ستتلقى بريدًا إلكترونيًا قريبًا.",
    toast_payslip: "جاري تحميل قسيمة الراتب...",
    timesheet: "الجدول الزمني الأسبوعي",
    timesheet_sub: "مراجعة ساعات عملك.",
    date: "التاريخ",
    in: "دخول",
    out: "خروج",
    hours: "الساعات",
    status: "الحالة",
    leave_req: "طلب إجازة",
    leave_req_sub: "التقدم بطلب للحصول على إجازة.",
    leave_type: "نوع الإجازة",
    start_date: "تاريخ البدء",
    end_date: "تاريخ الانتهاء",
    reason: "السبب",
    submit: "إرسال",
    pending_approvals: "الموافقات المعلقة",
    approved: "مقبول",
    pending: "قيد الانتظار",
    rejected: "مرفوض",
    salary_breakdown: "تفاصيل الراتب",
    salary_sub: "تفاصيل التعويض الشهري.",
    basic: "الراتب الأساسي",
    allowance: "السكن والنقل",
    deductions: "الضرائب والخصومات",
    net_pay: "صافي الراتب",
    recent_payslips: "قسائم الراتب الأخيرة",
    month: "الشهر",
    download: "تحميل",
    dash_no_announcements: "لا توجد إعلانات جديدة.",
    error_clock_in: "خطأ في تسجيل الدخول. تحقق من الاتصال بقاعدة البيانات.",
    success_clock_out: "تم تسجيل الخروج بنجاح.",
    error_clock_out: "خطأ في تسجيل الخروج.",
    failed_submit_leave: "فشل في تقديم الإجازة",
    leave_req_status: "تم تحديث حالة طلب الإجازة",
    time_punch_type: "نوع التسجيل",
    time_emp_id: "معرف الموظف",
    time_no_punches: "لا توجد تسجيلات وقت حديثة.",
    time_time: "الوقت",
    leave_no_reqs: "لم يتم العثور على طلبات إجازة.",
    leave_employee: "الموظف",
    leave_actions: "الإجراءات",
    leave_annual_bal: "رصيد الإجازة السنوية",
    leave_sick_bal: "رصيد الإجازة المرضية",
    leave_unpaid_bal: "الإجازة غير المدفوعة المتخذة",
    leave_days: "أيام",
    leave_new_req: "طلب جديد",
    leave_history: "سجل الطلبات",
    leave_reject: "رفض",
    req_all: "جميع الطلبات",
    req_sub: "عرض وتصفية جميع طلبات الإجازات والمستندات والنفقات.",
    req_search: "بحث",
    req_search_ph: "ابحث بالاسم أو التفاصيل...",
    req_type: "النوع",
    req_type_all: "جميع الأنواع",
    req_type_leave: "إجازة",
    req_type_doc: "مستند",
    req_type_exp: "نفقة",
    req_status: "الحالة",
    req_status_all: "جميع الحالات",
    req_pending: "قيد الانتظار",
    req_approved: "مقبول",
    req_rejected: "مرفوض",
    req_details: "التفاصيل",
    req_no_found: "لم يتم العثور على طلبات.",
    req_archived_title: "الطلبات المؤرشفة",
    req_archived_sub: "السجل التاريخي للطلبات المكتملة.",
    req_orig_status: "الحالة الأصلية",
    req_no_archived: "لم يتم العثور على طلبات مؤرشفة.",
    req_unauthorized: "غير مصرح لك. فقط المسؤولون والمديرون يمكنهم عرض الطلبات المؤرشفة.",
    req_archived_badge: "(مؤرشف)",
    req_archive_btn: "أرشفة",
    exp_title: "النفقات",
    exp_sub: "إدارة نفقات العمل والاسترداد.",
    exp_new: "تقديم نفقة جديدة",
    exp_amount: "المبلغ ($)",
    exp_desc: "الوصف",
    exp_receipt: "الإيصال",
    exp_submit: "تقديم النفقة",
    exp_my: "نفقاتي",
    exp_no_exp: "لا توجد نفقات.",
    exp_download: "تحميل",
    exp_team_appr: "موافقات نفقات الفريق",
    exp_no_pending: "لا توجد موافقات معلقة.",
    exp_req_receipt: "يرجى رفع الإيصال.",
    pay_latest: "أحدث قسيمة راتب",
    pay_base: "الراتب الأساسي",
    pay_extras: "العمل الإضافي/المكافأة",
    pay_view_det: "عرض التفاصيل",
    pay_no_slips: "لا توجد قسائم راتب متاحة.",
    pay_actions: "الإجراءات",
    analy_title: "التحليلات",
    analy_sub: "نظرة عامة على مقاييس الشركة.",
    analy_growth: "نمو الموظفين",
    analy_leave: "اتجاهات الإجازات",
    analy_unauth: "غير مصرح",
    admin_manage_tasks: "إدارة المهام",
    admin_time_reports: "تقارير الوقت",
    admin_emp_dir: "دليل الموظفين",
    admin_docs: "المستندات",
    admin_reg_users: "المستخدمين المسجلين",
    admin_pend_appr: "الموافقات المعلقة",
    admin_req_attn: "يتطلب الاهتمام",
    admin_leave_inbox: "صندوق الموافقات على الإجازات",
    admin_no_pending: "لا توجد طلبات إجازة معلقة.",
    users_sub: "إدارة حسابات الموظفين والصلاحيات.",
    users_add_new: "إضافة موظف جديد",
    users_fn: "الاسم الكامل",
    users_fn_ph: "مثال: أحمد محمد",
    users_iqama: "رقم الإقامة",
    users_iqama_ph: "مثال: 2xxxxxxxxx",
    users_phone: "رقم الهاتف",
    users_phone_ph: "مثال: +9665xxxxxxx",
    users_email: "البريد الإلكتروني",
    users_temp_pass: "كلمة مرور مؤقتة",
    users_job_title: "المسمى الوظيفي",
    users_job_ph: "مثال: مهندس برمجيات",
    users_role: "الدور",
    users_role_emp: "موظف",
    users_role_mgr: "مدير",
    users_role_admin: "مسؤول",
    users_create_acc: "إنشاء حساب",
    users_dir: "دليل الموظفين",
    users_details: "تفاصيل الموظف",
    users_assign_role: "تعيين الدور",
    users_assign_mgr: "تعيين المدير",
    users_contract: "العقد",
    users_no_mgr: "بدون مدير",
    contract_type: "نوع العقد",
    contract_ft: "دوام كامل",
    contract_pt: "دوام جزئي",
    contract_c: "مقاول",
    contract_fl: "عمل حر",
    contract_start: "تاريخ البدء",
    contract_end: "تاريخ الانتهاء (اختياري)",
    contract_salary: "الراتب (شهرياً)",
    contract_status: "الحالة",
    contract_active: "نشط",
    contract_term: "منهي",
    contract_exp: "منتهي",
    contract_cancel: "إلغاء",
    contract_save: "حفظ العقد",
    perf_sub: "تتبع مؤشرات الأداء والأهداف الخاصة بك.",
    perf_my_goals: "أهدافي",
    perf_title_th: "العنوان",
    perf_due_date: "تاريخ الاستحقاق",
    perf_rating: "التقييم",
    perf_no_goals: "لم يتم تعيين أي أهداف بعد.",
    doc_sub: "رفع المستندات الرسمية أو طلب خطابات الموارد البشرية.",
    doc_upload_title: "رفع مستند رسمي",
    doc_type: "نوع المستند",
    doc_file: "الملف",
    doc_upload_btn: "رفع المستند",
    doc_all_uploaded: "جميع المستندات المرفوعة",
    doc_my_uploaded: "مستنداتي المرفوعة",
    doc_file_name: "اسم الملف",
    doc_no_uploaded: "لا توجد مستندات مرفوعة.",
    doc_req_letter: "طلب خطاب",
    doc_purpose: "الغرض",
    doc_submit_req: "تقديم الطلب",
    doc_all_reqs: "جميع طلبات الخطابات",
    doc_my_reqs: "طلباتي",
    doc_no_reqs: "لم يتم العثور على طلبات.",
    doc_type_passport: "جواز السفر",
    doc_type_iqama: "إقامة",
    doc_type_contract: "عقد",
    doc_type_cert: "شهادة",
    doc_type_salary: "شهادة راتب",
    doc_type_noc: "شهادة عدم ممانعة",
    doc_type_emp: "خطاب عمل",
    msg_title: "الرسائل",
    msg_no_other: "لم يتم العثور على مستخدمين آخرين.",
    msg_select: "اختر مستخدماً لبدء المراسلة",
    msg_chat_with: "الدردشة مع",
    msg_refresh: "تحديث",
    msg_loading: "جاري تحميل الرسائل...",
    msg_type_ph: "اكتب رسالة...",
    msg_send: "إرسال",
    msg_no_msgs: "لا توجد رسائل بعد. قل مرحباً!",
    prof_sub: "إدارة إعدادات حسابك والمعلومات الشخصية.",
    prof_update_pic: "تحديث الصورة الشخصية",
    prof_upload_photo: "رفع الصورة",
    prof_acc_details: "تفاصيل الحساب",
    prof_fn: "الاسم الكامل",
    prof_email: "البريد الإلكتروني",
    prof_iqama: "رقم الإقامة",
    prof_phone: "رقم الهاتف",
    prof_save: "حفظ التغييرات",
    prof_security: "الأمان",
    prof_new_pass: "كلمة مرور جديدة",
    prof_new_pass_ph: "أدخل كلمة المرور الجديدة",
    prof_update_pass: "تحديث كلمة المرور",
    nav_tasks: "المهام",
    task_sub: "تتبع المشاريع وإدارة مهام الفريق.",
    task_assign_new: "تعيين مهمة جديدة",
    task_title: "عنوان المهمة",
    task_assign_to: "تعيين إلى",
    task_sel_emp: "اختر الموظف",
    task_due: "تاريخ الاستحقاق",
    task_assign_btn: "تعيين المهمة",
    task_due_lbl: "الاستحقاق:",
    task_no_date: "بدون تاريخ",
    task_assigned_lbl: "معينة لـ:",
    task_unknown: "غير معروف",
    task_todo: "للقيام بها",
    task_working: "جاري العمل",
    task_done: "مكتملة",
    task_no_tasks: "لا توجد مهام في هذه القائمة",
    nav_emp_dir: "الموظفون والعقود",
    emp_dir_sub: "دليل الموظفين وتفاصيل عقودهم.",
    emp_dir_company: "دليل الشركة",
    emp_name: "اسم الموظف",
    emp_contact: "معلومات الاتصال",
    emp_role_title: "الدور / المسمى الوظيفي",
    emp_na: "غير متوفر",
    emp_no_title: "بدون مسمى",
    notif_title: "الإشعارات",
    notif_login: "يرجى تسجيل الدخول لعرض الإشعارات.",
    notif_no_found: "لا توجد إشعارات.",
    notif_sub: "عرض جميع تنبيهات النظام والرسائل الخاصة بك.",
    notif_new: "جديد",
    notif_no_dropdown: "لا توجد إشعارات",
    nav_coming_soon: "قريباً",
    nav_under_const: "الوحدة قيد الإنشاء"
  }
};
