-- Persist document expiry states and track email notification delivery.
-- Safe to run after document_tracker_migration.sql.

BEGIN;

ALTER TABLE public.employee_documents
    ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'Active',
    ADD COLUMN IF NOT EXISTS last_notification_status TEXT,
    ADD COLUMN IF NOT EXISTS last_notified_at TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS last_notification_error TEXT;

UPDATE public.employee_documents
SET status = CASE
    WHEN expiration_date IS NULL THEN 'Active'
    WHEN expiration_date - CURRENT_DATE <= 0 THEN 'Expired'
    WHEN expiration_date - CURRENT_DATE <= 30 THEN 'Expires Soon'
    ELSE 'Active'
END;

ALTER TABLE public.employee_documents
    ALTER COLUMN status SET DEFAULT 'Active',
    ALTER COLUMN status SET NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'employee_documents_status_valid'
          AND conrelid = 'public.employee_documents'::regclass
    ) THEN
        ALTER TABLE public.employee_documents
            ADD CONSTRAINT employee_documents_status_valid
            CHECK (status IN ('Active', 'Expires Soon', 'Expired'));
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'employee_documents_notification_status_valid'
          AND conrelid = 'public.employee_documents'::regclass
    ) THEN
        ALTER TABLE public.employee_documents
            ADD CONSTRAINT employee_documents_notification_status_valid
            CHECK (
                last_notification_status IS NULL
                OR last_notification_status IN ('Expires Soon', 'Expired')
            );
    END IF;
END $$;

CREATE OR REPLACE FUNCTION public.set_employee_document_expiry_status()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
    NEW.status := CASE
        WHEN NEW.expiration_date IS NULL THEN 'Active'
        WHEN NEW.expiration_date - CURRENT_DATE <= 0 THEN 'Expired'
        WHEN NEW.expiration_date - CURRENT_DATE <= 30 THEN 'Expires Soon'
        ELSE 'Active'
    END;

    IF TG_OP = 'UPDATE' THEN
        IF NEW.expiration_date IS DISTINCT FROM OLD.expiration_date THEN
            NEW.last_notification_status := NULL;
            NEW.last_notified_at := NULL;
            NEW.last_notification_error := NULL;
        END IF;
    END IF;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS set_employee_document_expiry_status_trigger
    ON public.employee_documents;

CREATE TRIGGER set_employee_document_expiry_status_trigger
BEFORE INSERT OR UPDATE OF expiration_date
ON public.employee_documents
FOR EACH ROW
EXECUTE FUNCTION public.set_employee_document_expiry_status();

CREATE INDEX IF NOT EXISTS employee_documents_expiration_status_idx
    ON public.employee_documents(expiration_date, status)
    WHERE expiration_date IS NOT NULL;

CREATE TABLE IF NOT EXISTS public.document_expiry_notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_document_id UUID NOT NULL REFERENCES public.employee_documents(id) ON DELETE CASCADE,
    notification_status TEXT NOT NULL CHECK (notification_status IN ('Expires Soon', 'Expired')),
    recipient_email TEXT NOT NULL,
    expiration_date DATE NOT NULL,
    days_left INTEGER NOT NULL,
    sent_at TIMESTAMP WITH TIME ZONE,
    provider_message_id TEXT,
    error_message TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    UNIQUE (employee_document_id, notification_status, recipient_email, expiration_date)
);

ALTER TABLE public.document_expiry_notifications ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS document_expiry_notifications_lookup_idx
    ON public.document_expiry_notifications(employee_document_id, notification_status, expiration_date);

COMMIT;
