-- Document row actions and secure administrator password-reset support.
-- Apply this migration before deploying admin-set-user-password.

BEGIN;

CREATE OR REPLACE FUNCTION public.protect_profile_privileged_fields()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE caller_role TEXT;
BEGIN
    IF auth.uid() IS NULL THEN RETURN NEW; END IF;

    SELECT role INTO caller_role FROM public.profiles WHERE id = auth.uid();
    IF caller_role = 'ADMIN' THEN RETURN NEW; END IF;

    IF (to_jsonb(NEW) - ARRAY['full_name', 'iqama_number', 'phone_number', 'avatar_url', 'last_login', 'birth_date']::TEXT[])
       IS DISTINCT FROM
       (to_jsonb(OLD) - ARRAY['full_name', 'iqama_number', 'phone_number', 'avatar_url', 'last_login', 'birth_date']::TEXT[]) THEN
        RAISE EXCEPTION 'Only an administrator can change protected profile fields'
            USING ERRCODE = '42501';
    END IF;
    RETURN NEW;
END;
$$;

REVOKE ALL ON FUNCTION public.protect_profile_privileged_fields() FROM PUBLIC;
DROP TRIGGER IF EXISTS protect_profile_privileged_fields_trigger ON public.profiles;
CREATE TRIGGER protect_profile_privileged_fields_trigger
BEFORE UPDATE ON public.profiles
FOR EACH ROW EXECUTE FUNCTION public.protect_profile_privileged_fields();

CREATE OR REPLACE FUNCTION public.protect_employee_document_system_fields()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
    IF auth.uid() IS NOT NULL AND
       (to_jsonb(NEW) - ARRAY['doc_name', 'owner_name', 'owner_email', 'responsible_name', 'responsible_email', 'expiration_date', 'owner_phone']::TEXT[])
       IS DISTINCT FROM
       (to_jsonb(OLD) - ARRAY['doc_name', 'owner_name', 'owner_email', 'responsible_name', 'responsible_email', 'expiration_date', 'owner_phone']::TEXT[]) THEN
        RAISE EXCEPTION 'System-managed document fields cannot be changed from the app'
            USING ERRCODE = '42501';
    END IF;
    RETURN NEW;
END;
$$;

REVOKE ALL ON FUNCTION public.protect_employee_document_system_fields() FROM PUBLIC;
DROP TRIGGER IF EXISTS protect_employee_document_system_fields_trigger ON public.employee_documents;
CREATE TRIGGER protect_employee_document_system_fields_trigger
BEFORE UPDATE ON public.employee_documents
FOR EACH ROW EXECUTE FUNCTION public.protect_employee_document_system_fields();

DROP POLICY IF EXISTS "Authorized users can update employee documents" ON public.employee_documents;
CREATE POLICY "Authorized users can update employee documents"
ON public.employee_documents FOR UPDATE
USING (
    auth.uid() = employee_id
    OR EXISTS (SELECT 1 FROM public.profiles caller WHERE caller.id = auth.uid() AND caller.role = 'ADMIN')
    OR EXISTS (
        SELECT 1 FROM public.profiles caller
        JOIN public.profiles document_owner ON document_owner.id = employee_documents.employee_id
        WHERE caller.id = auth.uid()
          AND caller.role IN ('MANAGER', 'SUPERVISOR')
          AND document_owner.manager_id = auth.uid()
    )
)
WITH CHECK (
    auth.uid() = employee_id
    OR EXISTS (SELECT 1 FROM public.profiles caller WHERE caller.id = auth.uid() AND caller.role = 'ADMIN')
    OR EXISTS (
        SELECT 1 FROM public.profiles caller
        JOIN public.profiles document_owner ON document_owner.id = employee_documents.employee_id
        WHERE caller.id = auth.uid()
          AND caller.role IN ('MANAGER', 'SUPERVISOR')
          AND document_owner.manager_id = auth.uid()
    )
);

DROP POLICY IF EXISTS "Authorized users can delete employee documents" ON public.employee_documents;
CREATE POLICY "Authorized users can delete employee documents"
ON public.employee_documents FOR DELETE
USING (
    auth.uid() = employee_id
    OR EXISTS (SELECT 1 FROM public.profiles caller WHERE caller.id = auth.uid() AND caller.role = 'ADMIN')
    OR EXISTS (
        SELECT 1 FROM public.profiles caller
        JOIN public.profiles document_owner ON document_owner.id = employee_documents.employee_id
        WHERE caller.id = auth.uid()
          AND caller.role IN ('MANAGER', 'SUPERVISOR')
          AND document_owner.manager_id = auth.uid()
    )
);

CREATE TABLE IF NOT EXISTS public.admin_password_reset_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id UUID NOT NULL,
    target_user_id UUID NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);
ALTER TABLE public.admin_password_reset_audit ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.admin_password_reset_audit FROM anon, authenticated;
CREATE INDEX IF NOT EXISTS admin_password_reset_audit_actor_created_idx
    ON public.admin_password_reset_audit(actor_user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS admin_password_reset_audit_target_created_idx
    ON public.admin_password_reset_audit(target_user_id, created_at DESC);

DO $$
BEGIN
    IF to_regprocedure('public.reset_user_password(uuid,text)') IS NOT NULL THEN
        EXECUTE 'REVOKE EXECUTE ON FUNCTION public.reset_user_password(UUID, TEXT) FROM PUBLIC, anon, authenticated';
    END IF;
END $$;

COMMIT;
