const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const read = file => fs.readFileSync(path.join(root, file), 'utf8');
const sql = read('supabase/staging/productivity_phase_c.sql');
const deploy = read('supabase/staging/apply-productivity-phase-c.ps1');
const verify = read('supabase/staging/productivity-phase-c-readiness-test.ps1');
const cleanup = read('supabase/staging/cleanup-productivity-phase-c.ps1');
const db = read('js/db.js');
const app = read('js/app.js');
const services = read('js/shared-services.js');
const domain = read('src/shared/domain-services.ts');
const contract = read('src/shared/productivity-phase-c-contract.ts');
for (const fn of ['list_project_command_center','list_attention_needed','list_upcoming_events','get_project_health','get_project_operational_summary']) assert.match(sql, new RegExp(`FUNCTION public\\.${fn}\\b`), `missing ${fn}`);
assert.match(sql, /project\.event_date/);
assert.match(sql, /public\.task_dependency_blocked/);
assert.match(sql, /Project command center access denied/);
assert.match(sql, /REVOKE ALL ON FUNCTION/);
assert.match(sql, /GRANT EXECUTE ON FUNCTION/);
assert.match(sql, /reason_codes/);
assert.match(sql, /CRITICAL/);
assert.match(sql, /list_upcoming_events[\s\S]*ORDER BY \(item->>'event_date'\)::date ASC/);
assert.equal(/budget_amount|actual_cost|project_amount|paid_amount/.test(sql), false, 'command center must not expose financial fields');
assert.match(deploy, /jcfyyxsuspukcmybyhjj/);
assert.match(deploy, /bbbetcdioiaozdjkvwxu/);
assert.match(deploy, /SUPABASE_TELEMETRY_DISABLED/);
assert.match(deploy, /ExitCode/);
assert.match(verify, /UseBasicParsing|db.*query/i);
assert.match(verify, /jcfyyxsuspukcmybyhjj/);
assert.match(verify, /bbbetcdioiaozdjkvwxu/);
assert.match(verify, /create_project_secure/);
assert.match(verify, /create_task_secure/);
assert.match(verify, /get_project_operational_summary/);
assert.match(verify, /TEST-MANAGER/);
assert.match(verify, /cleanup_failed/);
assert.match(verify, /remove_task_dependency/);
assert.match(verify, /update_project_secure/);
assert.match(verify, /event_countdown/);
assert.match(verify, /synthetic_cleanup/);
assert.doesNotMatch(verify, /Select-Object\s+-Reverse/);
assert.match(cleanup, /jcfyyxsuspukcmybyhjj/);
assert.match(cleanup, /bbbetcdioiaozdjkvwxu/);
assert.match(cleanup, /UseBasicParsing/);
assert.match(cleanup, /PREVIOUS PHASE C SYNTHETIC CLEANUP: PASS/);
assert.doesNotMatch(cleanup, /auth\/v1|profiles|TEST-MANAGER|TEST-EMPLOYEE|TEST-OUTSIDER/);
assert.match(db, /rpc\('list_project_command_center'/);
assert.match(db, /rpc\('get_project_operational_summary'/);
assert.match(services, /projectCommandCenter/);
assert.match(domain, /projectCommandCenter/);
assert.match(contract, /ProjectHealthState/);
assert.match(app, /renderProjectCommandCenter/);
assert.match(app, /Attention needed/);
assert.match(app, /viewId === 'project-command-center'/);
console.log('PRODUCTIVITY PHASE C STATIC TESTS: PASS');
