import json
import re

translations = {
    "modal_body_are_you_sure_you_want_to_reset_this_user_s_password_and_unlock_their_account_": "هل أنت متأكد من رغبتك في إعادة تعيين كلمة مرور هذا المستخدم وإلغاء قفل حسابه؟",
    "ph_https_maps_google_com": "https://maps.google.com/...",
    "ph_e_g_slack_deal_notification": "مثال: إشعار صفقة Slack",
    "ph_https_hooks_slack_com_services": "https://hooks.slack.com/services/...",
    "ph_enter_full_name": "أدخل الاسم الكامل",
    "ph_optional": "اختياري",
    "ph_e_g_developer": "مثال: مطور",
    "ph_e_g_graphic_video": "مثال: تصميم جرافيك، فيديو",
    "ph_https": "https://...",
    "ph_e_g_5_hours": "مثال: 5 ساعات",
    "ph_add_a_comment": "أضف تعليقاً...",
    "html_user": "مستخدم",
    "html_role": "الدور",
    "html_new_client": "عميل جديد",
    "html_deal_details": "تفاصيل الصفقة",
    "html_select_method": "اختر الطريقة",
    "html_phone_call": "مكالمة هاتفية",
    "html_whatsapp": "واتساب",
    "html_social_media": "وسائل التواصل الاجتماعي",
    "html_deal_lost_reason": "سبب خسارة الصفقة",
    "html_why_was_this_deal_lost": "لماذا تم خسارة هذه الصفقة؟ *",
    "html_order_details": "تفاصيل الطلب",
    "html_not_confirmed": "غير مؤكد",
    "html_in_progress": "قيد التنفيذ",
    "html_completed": "مكتمل",
    "html_edit_order": "تعديل الطلب",
    "html_delete_order": "حذف الطلب؟",
    "html_are_you_sure_you_want_to_permanently_delete_this_order_this_action_cannot_be_undone": "هل أنت متأكد من رغبتك في حذف هذا الطلب نهائياً؟ هذا الإجراء لا يمكن التراجع عنه.",
    "html_cancel": "إلغاء",
    "html_delete": "حذف",
    "html_new_webhook": "رابط ويب (Webhook) جديد",
    "html_integration_name": "اسم التكامل *",
    "html_target_url_post": "رابط الوجهة (POST) *",
    "html_trigger_event": "حدث التشغيل *",
    "html_all_events": "جميع الأحداث",
    "html_deal_won": "الصفقة الرابحة",
    "html_new_client_added": "تمت إضافة عميل جديد",
    "html_new_task_created": "تم إنشاء مهمة جديدة",
    "html_task_details_updated": "تم تحديث تفاصيل المهمة",
    "html_task_status_updated": "تم تحديث حالة المهمة",
    "html_task_deleted": "تم حذف المهمة",
    "html_save_webhook": "حفظ رابط الويب (Webhook)",
    "html_employee": "موظف",
    "html_manager": "مدير",
    "html_supervisor": "مشرف",
    "html_admin": "مسؤول",
    "html_no_manager": "لا يوجد مدير",
    "html_save_changes": "حفظ التغييرات",
    "html_delete_user": "حذف المستخدم",
    "html_are_you_sure_you_want_to_delete_this_user": "هل أنت متأكد من رغبتك في حذف هذا المستخدم؟",
    "html_this_action_cannot_be_undone": "هذا الإجراء لا يمكن التراجع عنه.",
    "html_request_type": "نوع الطلب",
    "html_leave_request": "طلب إجازة",
    "html_it_support": "دعم تقنية المعلومات",
    "html_loan": "قرض",
    "html_early_leaving": "انصراف مبكر",
    "html_payslip_print": "طباعة مسير الرواتب",
    "html_leave_type": "نوع الإجازة",
    "html_annual_vacation": "سنوية/عطلة",
    "html_sick_leave": "إجازة مرضية",
    "html_unpaid_leave": "إجازة بدون راتب",
    "html_bereavement": "إجازة وفاة",
    "html_maternity_paternity": "إجازة أمومة/أبوة",
    "html_submit_request": "تقديم الطلب",
    "html_new_department": "قسم جديد",
    "html_department_name": "اسم القسم *",
    "html_description": "الوصف",
    "html_department_head": "رئيس القسم",
    "html_department_employees": "موظفي القسم",
    "html_create_department": "إنشاء قسم",
    "html_new_project": "مشروع جديد",
    "html_select_type": "اختر النوع...",
    "html_internal": "داخلي",
    "html_client": "عميل",
    "html_product": "منتج",
    "html_maintenance": "صيانة",
    "html_startup": "بدء تشغيل",
    "html_enterprise": "مؤسسة",
    "html_urgent": "عاجل",
    "html_frontend": "واجهة أمامية",
    "html_backend": "واجهة خلفية",
    "html_ui_ux": "واجهة/تجربة المستخدم",
    "html_bug": "خطأ برمجي",
    "html_feature": "ميزة",
    "html_create_project": "إنشاء مشروع",
    "html_edit_project": "تعديل المشروع",
    "html_confirm_action": "تأكيد الإجراء",
    "html_are_you_sure": "هل أنت متأكد؟",
    "html_confirm": "تأكيد",
    "html_edit_task": "تعديل المهمة",
    "html_task_title": "عنوان المهمة",
    "html_category": "الفئة",
    "html_priority": "الأولوية",
    "html_low": "منخفضة",
    "html_medium": "متوسطة",
    "html_high": "عالية",
    "html_project": "المشروع",
    "html_assign_to": "إسناد إلى",
    "html_content_type": "نوع المحتوى",
    "html_source_link": "رابط المصدر",
    "html_upload_link": "رابط الرفع",
    "html_visibility": "الظهور",
    "html_public_everyone": "عام (للجميع)",
    "html_team_only": "للفريق فقط",
    "html_private": "خاص",
    "html_start_date": "تاريخ البدء",
    "html_due_date": "تاريخ الاستحقاق",
    "html_end_date": "تاريخ الانتهاء",
    "html_est_time": "الوقت المقدر",
    "html_task_details": "تفاصيل المهمة",
    "html_activity_comments": "النشاط والتعليقات",
    "html_send": "إرسال"
}

with open('e:/HR.sys/scratch/translations1.json', 'w', encoding='utf-8') as f:
    json.dump(translations, f, ensure_ascii=False, indent=4)
